// Málaga Open — roster data. Real lists pulled from Best Coast Pairings
// (https://web.bestcoastpairings.com/event/GBTKjKjtPM47) on 2026-07-13.
// Each player = { id, name, team, faction, dispo, summary, list }

export const FACTION_COLORS = {
  "Necrons": "#30A46C",
  "Blood Angels": "#E5484D",
  "Space Marines": "#0A84FF",
  "Chaos Space Marines": "#8E4EC6",
  "Adeptus Mechanicus": "#E5484D",
  "Adeptus Custodes": "#B08A00",
  "Emperor's Children": "#D6409F",
  "Astra Militarum": "#8F8B5C",
  "Imperial Knights": "#F76B15",
  "T'au Empire": "#00A2C7",
  "Orks": "#46A758",
  "World Eaters": "#DC3E42",
};

export const MAP_POOLS = {
  "Take and Hold": [
    { layout: "Layout 2", deployment: "Hammer & Anvil" },
    { layout: "Layout 4", deployment: "Search & Destroy" },
    { layout: "Layout 6", deployment: "Crucible of Battle" },
  ],
  "Purge the Foe": [
    { layout: "Layout 1", deployment: "Dawn of War" },
    { layout: "Layout 3", deployment: "Sweeping Engagement" },
    { layout: "Layout 8", deployment: "Hammer & Anvil" },
  ],
  "Priority Assets": [
    { layout: "Layout 2", deployment: "Crucible of Battle" },
    { layout: "Layout 5", deployment: "Dawn of War" },
    { layout: "Layout 7", deployment: "Search & Destroy" },
  ],
  "Reconnaissance": [
    { layout: "Layout 3", deployment: "Hammer & Anvil" },
    { layout: "Layout 6", deployment: "Sweeping Engagement" },
    { layout: "Layout 8", deployment: "Tipping Point" },
  ],
  "Disruption": [
    { layout: "Layout 1", deployment: "Crucible of Battle" },
    { layout: "Layout 4", deployment: "Dawn of War" },
    { layout: "Layout 7", deployment: "Tipping Point" },
  ],
};

// Primary mission = MISSION_MATRIX[yourDispo][opponentDispo] (GDM 2026, 11th ed.)
export const MISSION_MATRIX = {
  "Take and Hold": {
    "Take and Hold": "Battlefield Dominance",
    "Purge the Foe": "Immovable Object",
    "Disruption": "Determined Acquisition",
    "Reconnaissance": "Purge and Secure",
    "Priority Assets": "Inescapable Dominion",
  },
  "Purge the Foe": {
    "Take and Hold": "Unstoppable Force",
    "Purge the Foe": "Meatgrinder",
    "Disruption": "Punishment",
    "Reconnaissance": "Consecrate",
    "Priority Assets": "Destroyer's Wrath",
  },
  "Disruption": {
    "Take and Hold": "Death Trap",
    "Purge the Foe": "Delaying Action",
    "Disruption": "Outmanoeuvre",
    "Reconnaissance": "Smoke and Mirrors",
    "Priority Assets": "Locate and Deny",
  },
  "Reconnaissance": {
    "Take and Hold": "Reconnaissance Sweep",
    "Purge the Foe": "Triangulation",
    "Disruption": "Surveil the Foe",
    "Reconnaissance": "Gather Intel",
    "Priority Assets": "Search and Scour",
  },
  "Priority Assets": {
    "Take and Hold": "Secure Asset",
    "Purge the Foe": "Vital Link",
    "Disruption": "Extract Relic",
    "Reconnaissance": "Vanguard Operation",
    "Priority Assets": "Sabotage",
  },
};

const u = (qty, name, pts, gear) => ({ qty, name, pts, gear });

export const PLAYERS = [
  {
    id: "dimitri", name: "Dimitri Farber Garcia", team: "Legio Veteris",
    faction: "Space Marines", dispo: "Take and Hold",
    summary: { detachment: "Ultramarines · Librarius Conclave & Reclamation Force", warlord: "Marneus Calgar", points: 2000, units: 17, enhancements: ["Fusillade (Librarian)"], secondaries: "" },
    list: [
      u(1, "Marneus Calgar in Armour of Antilochus", 140, "Warlord, Gauntlets of Ultramar — leads Assault Terminators"),
      u(5, "Terminator Assault Squad", 170, "Thunder hammers & storm shields, twin lightning claws"),
      u(1, "Captain Titus", 90, "Master-crafted bolter & chainsword — leads Wardens + Bladeguard"),
      u(6, "Wardens of Ultramar", 110, "Gadriel, Metaurus, Silva, Minervas, Komelius, Vestha"),
      u(6, "Bladeguard Veteran Squad", 160, "Master-crafted power weapons, neo-volkite pistol"),
      u(1, "Librarian", 80, "Fusillade, Force weapon — leads Sternguard"),
      u(10, "Sternguard Veteran Squad", 190, "Sternguard bolt rifles, 2x heavy bolter, power fist"),
      u(1, "Lieutenant with Combi-weapon", 85, "Combi-weapon, Paired combat blades"),
      u(5, "Intercessor Squad", 80, "Bolt rifles, grenade launcher, power fist"),
      u(5, "Assault Intercessors w/ Jump Packs", 85, "Chainswords, plasma pistol, power fist"),
      u(1, "Ballistus Dreadnought", 150, "Ballistus lascannon & missile launcher"),
      u(1, "Ballistus Dreadnought", 150, "Ballistus lascannon & missile launcher"),
      u(5, "Incursor Squad", 85, "Occulus bolt carbines, haywire mine"),
      u(1, "Land Speeder", 95, "Multi-melta, gatling cannon, Stormfury missiles"),
      u(1, "Land Speeder", 95, "Multi-melta, gatling cannon, Stormfury missiles"),
      u(1, "Repulsor", 170, "Heavy onslaught gatling cannon, twin heavy bolter"),
      u(5, "Scout Squad", 65, "Shotguns, heavy bolter, sniper rifle"),
    ],
  },
  {
    id: "miguel", name: "Miguel Puerta Rodriguez", team: "LEGIO IX HISPANA",
    faction: "Necrons", dispo: "Take and Hold",
    summary: {
      detachment: "Awakened Dynasty (Command Protocols)", warlord: "Imotekh the Stormlord", points: 2000, units: 16,
      enhancements: ["Nether-realm Casket (Royal Warden)", "Enaegic Dermal Bond (Skorpekh Lord)"],
      secondaries: "Bring It Down: (2x2) + (1x4) — Assassination: 9 Characters — Cull The Horde: 1x5 (before leaders attached)",
    },
    list: [
      u(1, "C'tan Shard of the Deceiver", 330, "Cosmic insanity, Golden fists"),
      u(1, "Catacomb Command Barge", 120, "Resurrection orb, Gauss cannon, Overlord's blade"),
      u(1, "Illuminor Szeras", 175, "Eldritch lance, Impaling legs"),
      u(1, "Imotekh the Stormlord", 100, "Warlord, Gauntlet of Fire, Staff of the Destroyer"),
      u(1, "Orikan the Diviner", 90, "Staff of Tomorrow — leads Necron Warriors"),
      u(1, "Overlord", 90, "Resurrection orb, Voidscythe"),
      u(1, "Royal Warden", 90, "Relic gauss blaster — Nether-realm Casket (+20) — leads Necron Warriors"),
      u(1, "Skorpekh Lord", 150, "Enmitic annihilator, Flensing claw, Hyperphase harvester — Enaegic Dermal Bond (+30)"),
      u(1, "Technomancer", 80, "Staff of light — leads Canoptek Wraiths"),
      u(20, "Necron Warriors", 190, "Close combat weapons, Gauss reapers"),
      u(1, "Canoptek Reanimator", 70, "2x Atomiser beam, Reanimator's claws"),
      u(2, "Canoptek Tomb Crawlers", 50, "Claws, Twin gauss reaper / Dimensional isolator — moves with Warriors"),
      u(6, "Canoptek Wraiths", 220, "Particle casters, Vicious claws"),
      u(5, "Flayed Ones", 55, "Flayer claws"),
      u(10, "Lychguard", 160, "Dispersion shields, Hyperphase swords"),
      u(3, "Ophydian Destroyers", 80, "Plasmacyte, Ophydian hyperphase weapons"),
    ],
  },
  {
    id: "angel-c", name: "Angel Cañamero", team: "El Ordo Autista",
    faction: "Blood Angels", dispo: "Purge the Foe",
    summary: { detachment: "The Angelic Host & Wrath of the Doomed", warlord: "Commander Dante", points: 2000, units: 14, enhancements: ["Gleaming Pinions (Captain w/ Jump Pack)"], secondaries: "" },
    list: [
      u(1, "Commander Dante", 125, "Warlord, The Axe Mortalis, Perdition Pistol — leads Sanguinary Guard"),
      u(6, "Sanguinary Guard", 260, "Encarmine spears, Angelus boltguns, Sanguinary Banner"),
      u(1, "Astorath", 85, "The Executioner's Axe — leads Death Company"),
      u(5, "Death Company w/ Jump Packs", 120, "Chainswords, eviscerator, power fists"),
      u(1, "Death Company Captain w/ Jump Pack", 75, "Plasma pistol, Power fist — leads Death Company"),
      u(5, "Death Company w/ Jump Packs", 135, "Chainswords, eviscerator, power fists"),
      u(1, "Lemartes", 100, "The Blood Crozius — leads Death Company"),
      u(10, "Death Company w/ Jump Packs", 230, "Chainswords, eviscerators, power fists"),
      u(1, "Captain with Jump Pack", 105, "Gleaming Pinions, Thunder hammer, Relic Shield — leads Sanguinary Guard"),
      u(6, "Sanguinary Guard", 260, "Encarmine spears, Angelus boltguns, Sanguinary Banner"),
      u(1, "Baal Predator", 125, "Baal flamestorm cannon, heavy flamers"),
      u(1, "Death Company Dreadnought", 150, "Blood talons, twin multi-melta"),
      u(3, "Inceptor Squad", 120, "Assault bolters"),
      u(5, "Infiltrator Squad", 110, "Marksman bolt carbines, helix gauntlet, comms array"),
    ],
  },
  {
    id: "boris", name: "Boris Hollander", team: "—",
    faction: "Chaos Space Marines", dispo: "Disruption",
    summary: { detachment: "Huron's Marauders", warlord: "Sorcerer in Terminator Armour", points: 1980, units: 17, enhancements: ["Infernal Gaze (Sorcerer)", "Raid Leader (Master of Executions)"], secondaries: "" },
    list: [
      u(1, "Sorcerer in Terminator Armour", 80, "Warlord, Infernal Gaze, Force weapon — leads Terminators"),
      u(5, "Chaos Terminator Squad", 180, "Combi-bolters, chainfist, reaper autocannon, power fists"),
      u(1, "Master of Executions", 90, "Raid Leader, Axe of dismemberment — with Chosen"),
      u(10, "Chosen", 250, "Accursed weapons, plasma pistols, power fists, icon"),
      u(1, "Chaos Lord with Jump Pack", 90, "Plasma pistol, Power fist — leads Raptors"),
      u(5, "Raptors", 110, "Heavy melee weapons, meltagun"),
      u(10, "Cultist Mob", 50, "Autopistols, brutal assault weapons"),
      u(10, "Cultist Mob", 50, "Autopistols, brutal assault weapons"),
      u(5, "Legionaries", 90, "Heavy melee weapons, meltagun, icon"),
      u(1, "Chaos Rhino", 75, "Combi-bolters, havoc launcher"),
      u(3, "Chaos Bikers", 70, "Combi-bolters, power fist, icon"),
      u(5, "Havocs", 125, "4x Havoc lascannon, power fist, meltagun"),
      u(3, "Mutilators", 180, "Fleshmetal weapons"),
      u(2, "Obliterators", 160, "Fleshmetal guns, crushing fists"),
      u(2, "Obliterators", 160, "Fleshmetal guns, crushing fists"),
      u(5, "Raptors", 110, "Heavy melee weapons, meltagun"),
      u(5, "Red Corsairs Raiders", 110, "Reaver's blades, meltagun, power fist"),
    ],
  },
  {
    id: "capitan", name: "Capitán Mechero", team: "El Ordo Autista",
    faction: "Adeptus Mechanicus", dispo: "Priority Assets",
    summary: { detachment: "Cohort Cybernetica & Forge Lords", warlord: "Belisarius Cawl", points: 2000, units: 17, enhancements: ["Vingh's Dynamic Programming (Datasmith)", "Lord of Machines (Manipulus)", "Necromechanic (Enginseer)"], secondaries: "" },
    list: [
      u(1, "Cybernetica Datasmith", 50, "Vingh's Dynamic Programming, Power fist — leads Kastelans"),
      u(4, "Kastelan Robots", 320, "Incendine combustors, twin Kastelan fists"),
      u(1, "Tech-Priest Manipulus", 75, "Lord of Machines, Magnarail lance — leads Breachers"),
      u(3, "Kataphron Breachers", 150, "Heavy arc rifles, hydraulic claws"),
      u(1, "Belisarius Cawl", 220, "Warlord, Solar atomiser, Cawl's Omnissian axe"),
      u(1, "Tech-Priest Enginseer", 75, "Necromechanic, Omnissian axe, servo-arm"),
      u(1, "Thulia Ghuld", 180, "Rod of the War Forge, Jericho conversion resonator"),
      u(10, "Skitarii Rangers", 85, "Galvanic rifles, transuranic arquebus, plasma caliver, arc rifle"),
      u(10, "Skitarii Rangers", 85, "Galvanic rifles, transuranic arquebus, plasma caliver, arc rifle"),
      u(2, "Ironstrider Ballistarii", 180, "Twin cognis lascannons"),
      u(1, "Onager Dunecrawler", 155, "Neutron laser, cognis heavy stubbers"),
      u(3, "Serberys Raiders", 60, "Galvanic carbines, cavalry sabres"),
      u(9, "Servitor Battleclade", 65, "Heavy arc rifle, heavy bolter, incendine igniters, servo-claws"),
      u(5, "Sicarian Infiltrators", 75, "Flechette blasters, taser goads"),
      u(5, "Sicarian Infiltrators", 75, "Flechette blasters, taser goads"),
      u(5, "Sicarian Ruststalkers", 75, "Transonic razors and chordclaws"),
      u(5, "Sicarian Ruststalkers", 75, "Transonic razors and chordclaws"),
    ],
  },
  {
    id: "coronel", name: "Coronel T.H.", team: "El Ordo Autista",
    faction: "Necrons", dispo: "Reconnaissance",
    summary: { detachment: "Cryptek Conclave & Skyshroud Spearhead", warlord: "Nekrosor Ammentar", points: 2000, units: 16, enhancements: ["Quantum Abacus (Technomancer)", "Atomic Disintegrators (Technomancer)", "Gravitic Bolas (Chronomancer)"], secondaries: "" },
    list: [
      u(1, "Technomancer", 95, "Quantum Abacus, Staff of light — leads Canoptek Wraiths"),
      u(6, "Canoptek Wraiths", 220, "Particle casters, vicious claws"),
      u(1, "Technomancer", 100, "Atomic Disintegrators, Staff of light — leads Canoptek Wraiths"),
      u(6, "Canoptek Wraiths", 240, "Particle casters, vicious claws"),
      u(1, "Chronomancer", 95, "Gravitic Bolas, Chronomancer's stave — leads Immortals"),
      u(5, "Immortals", 70, "Gauss blasters"),
      u(1, "C'tan Shard of the Nightbringer", 360, "Gaze of death, Scythe of the Nightbringer"),
      u(1, "Nekrosor Ammentar", 175, "Warlord, Unmaker Gauntlet, Nullstone Field Generator"),
      u(5, "Immortals", 70, "Gauss blasters"),
      u(1, "Doomsday Ark", 200, "Doomsday cannon, gauss flayer arrays"),
      u(5, "Flayed Ones", 55, "Flayer claws"),
      u(1, "Lokhust Destroyers", 40, "Gauss cannon"),
      u(1, "Lokhust Destroyers", 40, "Gauss cannon"),
      u(1, "Lokhust Heavy Destroyers", 50, "Gauss destructor"),
      u(1, "Lokhust Heavy Destroyers", 50, "Enmitic exterminator"),
      u(6, "Tomb Blades", 140, "Particle beamers, nebuloscopes"),
    ],
  },
  {
    id: "forthemperor", name: "For the Emperor", team: "1UP",
    faction: "Space Marines", dispo: "Priority Assets",
    summary: { detachment: "Imperial Fists · 1st Company Task Force & Librarius Conclave", warlord: "Darnath Lysander", points: 2000, units: 14, enhancements: ["Iron Resolve (Ancient)", "Fusillade (Librarian)", "Temporal Corridor (Librarian in Terminator Armour)"], secondaries: "" },
    list: [
      u(1, "Darnath Lysander", 100, "Warlord, Fist of Dorn — leads Assault Terminators"),
      u(1, "Ancient in Terminator Armour", 80, "Iron Resolve, Thunder hammer & storm shield — with Assault Terminators"),
      u(10, "Terminator Assault Squad", 330, "Thunder hammers, storm shields, twin lightning claws"),
      u(1, "Librarian", 80, "Fusillade, Force weapon — leads Sternguard"),
      u(10, "Sternguard Veteran Squad", 190, "Sternguard bolt rifles, power fist"),
      u(1, "Librarian in Terminator Armour", 90, "Temporal Corridor, Storm bolter — leads Terminators"),
      u(10, "Terminator Squad", 320, "Power fists, storm bolters, 2x cyclone missile launcher"),
      u(1, "Lieutenant with Combi-weapon", 85, "Combi-weapon, Paired combat blades"),
      u(1, "Ballistus Dreadnought", 150, "Ballistus lascannon & missile launcher"),
      u(1, "Ballistus Dreadnought", 150, "Ballistus lascannon & missile launcher"),
      u(1, "Land Speeder", 95, "Multi-melta, gatling cannon, Stormfury missiles"),
      u(1, "Land Speeder", 95, "Multi-melta, gatling cannon, Stormfury missiles"),
      u(1, "Repulsor", 170, "Heavy onslaught gatling cannon, twin heavy bolter"),
      u(5, "Scout Squad", 65, "Missile launcher, sniper rifle, boltguns"),
    ],
  },
  {
    id: "francisco", name: "Francisco Javier Domínguez Granado", team: "Legio Veteris",
    faction: "Space Marines", dispo: "Purge the Foe",
    summary: { detachment: "Salamanders · Forgefather's Seekers & Librarius Conclave", warlord: "Vulkan He'stan", points: 2000, units: 15, enhancements: ["Temporal Corridor (Librarian)", "Immolator (Librarian)", "Fusillade (Librarian)", "Forged in Battle (Librarian in Terminator Armour)"], secondaries: "" },
    list: [
      u(1, "Librarian", 75, "Temporal Corridor, Force weapon — leads Infernus"),
      u(10, "Infernus Squad", 170, "Pyreblasters"),
      u(1, "Librarian", 70, "Immolator, Force weapon — leads Infernus"),
      u(10, "Infernus Squad", 170, "Pyreblasters"),
      u(1, "Librarian", 80, "Fusillade, Force weapon — leads Sternguard"),
      u(10, "Sternguard Veteran Squad", 190, "Sternguard bolt rifles, 2x heavy bolter, power weapon"),
      u(1, "Librarian in Terminator Armour", 90, "Forged in Battle, Storm bolter — leads Terminators"),
      u(5, "Terminator Squad", 160, "Power fists, storm bolters, cyclone missile launcher"),
      u(1, "Lieutenant with Combi-weapon", 85, "Combi-weapon, Paired combat blades"),
      u(1, "Vulkan He'stan", 85, "Warlord, Spear of Vulkan, Gauntlet of the Forge"),
      u(1, "Ballistus Dreadnought", 150, "Ballistus lascannon & missile launcher"),
      u(1, "Ballistus Dreadnought", 150, "Ballistus lascannon & missile launcher"),
      u(5, "Incursor Squad", 85, "Occulus bolt carbines, haywire mine"),
      u(1, "Land Raider", 220, "Godhammer lascannons, multi-melta"),
      u(1, "Land Raider", 220, "Godhammer lascannons, multi-melta"),
    ],
  },
  {
    id: "israel", name: "Israel Caballeros del Caos", team: "Legio Veteris",
    faction: "Emperor's Children", dispo: "Priority Assets",
    summary: { detachment: "Peerless Bladesmen & Frenzied Host", warlord: "Daemon Prince of Slaanesh with Wings", points: 1985, units: 15, enhancements: ["Distortion (Lord Exultant)", "Faultless Opportunist (Daemon Prince)"], secondaries: "" },
    list: [
      u(1, "Lucius the Eternal", 130, "Blade of the Laer, Lash of Torment — leads Flawless Blades"),
      u(3, "Flawless Blades", 95, "Blissblades"),
      u(1, "Lord Exultant", 105, "Distortion, Phoenix power spear — leads Infractors"),
      u(5, "Infractors", 85, "Duelling sabres, Icon of Excess"),
      u(1, "Lord Exultant", 80, "Phoenix power spear — leads Infractors"),
      u(5, "Infractors", 85, "Duelling sabres, Icon of Excess"),
      u(1, "Lord Exultant", 90, "Phoenix power spear — leads Infractors"),
      u(5, "Infractors", 85, "Duelling sabres, Icon of Excess"),
      u(1, "Daemon Prince of Slaanesh with Wings", 220, "Warlord, Faultless Opportunist, Infernal cannon"),
      u(5, "Tormentors", 80, "Meltagun, plasma gun, Icon of Excess"),
      u(1, "Chaos Rhino", 80, "Combi-bolters, havoc launcher"),
      u(2, "Chaos Spawn", 70, "Hideous mutations"),
      u(1, "Defiler", 310, "Ectoplasma destructor, Hades lascannons, shearing claws"),
      u(1, "Defiler", 340, "Ectoplasma destructor, Hades lascannons, shearing claws"),
      u(1, "Maulerfiend", 130, "Maulerfiend fists, magma cutters"),
    ],
  },
  {
    id: "josemanuel", name: "Jose Manuel Aguilar Rodriguez", team: "LEGIO IX HISPANA",
    faction: "Adeptus Custodes", dispo: "Purge the Foe",
    summary: { detachment: "Lions of the Emperor & Might of the Moritoi", warlord: "Shield-Captain in Allarus Terminator Armour", points: 2000, units: 14, enhancements: [], secondaries: "" },
    list: [
      u(1, "Shield-Captain in Allarus Terminator Armour", 130, "Warlord, Castellan axe, balistus grenade launcher — leads Allarus"),
      u(2, "Allarus Custodians", 110, "Guardian spears, balistus grenade launchers"),
      u(1, "Blade Champion", 125, "Vaultswords — leads Custodian Wardens"),
      u(5, "Custodian Wardens", 260, "Guardian spears"),
      u(1, "Blade Champion", 110, "Vaultswords — leads Custodian Wardens"),
      u(5, "Custodian Wardens", 280, "Guardian spears"),
      u(5, "Custodian Guard", 215, "Guardian spears"),
      u(2, "Allarus Custodians", 110, "Guardian spears, balistus grenade launchers"),
      u(1, "Caladius Grav-tank", 225, "Twin arachnus heavy blaze cannon"),
      u(1, "Caladius Grav-tank", 225, "Twin arachnus heavy blaze cannon"),
      u(5, "Prosecutors", 50, "Boltguns"),
      u(5, "Prosecutors", 50, "Boltguns"),
      u(5, "Witchseekers", 55, "Witchseeker flamers"),
      u(5, "Witchseekers", 55, "Witchseeker flamers"),
    ],
  },
  {
    id: "juanignacio", name: "Juan Ignacio Dacrov", team: "—",
    faction: "Space Marines", dispo: "Priority Assets",
    summary: { detachment: "Ultramarines · Gladius Task Force", warlord: "Marneus Calgar", points: 2000, units: 15, enhancements: ["The Honour Vehement (Techmarine)"], secondaries: "" },
    list: [
      u(1, "Marneus Calgar in Armour of Antilochus", 140, "Warlord, Gauntlets of Ultramar — leads Victrix Guard"),
      u(7, "Victrix Honour Guard", 240, "Master-crafted power weapons, Banner of Macragge"),
      u(1, "Uriel Ventris", 95, "Invictus, Sword of Idaeus — leads Bladeguard"),
      u(6, "Bladeguard Veteran Squad", 160, "Master-crafted power weapons, plasma pistol"),
      u(1, "Lieutenant with Combi-weapon", 85, "Combi-weapon, Paired combat blades"),
      u(1, "Techmarine", 70, "The Honour Vehement, Forge bolter"),
      u(1, "Techmarine", 55, "Forge bolter, Omnissian power axe"),
      u(5, "Assault Intercessors w/ Jump Packs", 85, "Chainswords, plasma pistols, power fist"),
      u(5, "Assault Intercessors w/ Jump Packs", 85, "Chainswords, plasma pistols, power fist"),
      u(5, "Infiltrator Squad", 110, "Marksman bolt carbines"),
      u(5, "Infiltrator Squad", 110, "Marksman bolt carbines"),
      u(1, "Land Raider", 220, "Godhammer lascannons, multi-melta"),
      u(1, "Repulsor Executioner", 240, "Heavy laser destroyer, Icarus rocket pod"),
      u(1, "Repulsor Executioner", 240, "Heavy laser destroyer, Icarus rocket pod"),
      u(5, "Scout Squad", 65, "Shotguns, missile launcher, sniper rifle"),
    ],
  },
  {
    id: "juanjose", name: "Juan José Wu", team: "Gondor 40K",
    faction: "Blood Angels", dispo: "Take and Hold",
    summary: { detachment: "Liberator Assault Group", warlord: "Commander Dante", points: 1990, units: 18, enhancements: [], secondaries: "" },
    list: [
      u(1, "Commander Dante", 125, "Warlord, The Axe Mortalis, Perdition Pistol — leads Sanguinary Guard"),
      u(6, "Sanguinary Guard", 260, "Encarmine blades, Angelus boltguns, Sanguinary Banner"),
      u(1, "Lemartes", 100, "The Blood Crozius — leads Death Company"),
      u(10, "Death Company w/ Jump Packs", 230, "Chainswords, eviscerators, power fists"),
      u(1, "Captain with Jump Pack", 80, "Hand flamer, Power fist — leads Sanguinary Guard"),
      u(3, "Sanguinary Guard", 125, "Encarmine blades, Angelus boltguns"),
      u(1, "Chief Librarian Mephiston", 110, "Vitarus, Fury of the Ancients, plasma pistol"),
      u(1, "Lieutenant with Combi-weapon", 85, "Combi-weapon, Paired combat blades"),
      u(5, "Assault Intercessor Squad", 80, "Chainswords, heavy bolt pistols"),
      u(5, "Assault Intercessor Squad", 80, "Chainswords, heavy bolt pistols"),
      u(5, "Intercessor Squad", 80, "Bolt rifles, grenade launcher, power fist"),
      u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, plasma pistol, power weapon"),
      u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, plasma pistol, power weapon"),
      u(1, "Baal Predator", 125, "Baal flamestorm cannon, heavy flamers"),
      u(1, "Land Speeder", 95, "Multi-melta, gatling cannon, Stormfury missiles"),
      u(1, "Land Speeder", 95, "Multi-melta, gatling cannon, Stormfury missiles"),
      u(5, "Scout Squad", 65, "Missile launcher, boltguns"),
      u(5, "Scout Squad", 65, "Missile launcher, boltguns"),
    ],
  },
  {
    id: "juanma", name: "Juanma Melilla", team: "Diario de un Recluta",
    faction: "Space Marines", dispo: "Purge the Foe",
    summary: { detachment: "Salamanders · Librarius Conclave & Forgefather's Seekers", warlord: "Vulkan He'stan", points: 1965, units: 13, enhancements: ["Immolator (Captain in Gravis Armour)", "Temporal Corridor (Librarian)", "Fusillade (Librarian)"], secondaries: "" },
    list: [
      u(1, "Vulkan He'stan", 85, "Warlord, Spear of Vulkan, Gauntlet of the Forge — leads Infernus"),
      u(5, "Infernus Squad", 85, "Pyreblasters"),
      u(1, "Captain in Gravis Armour", 90, "Immolator, Relic blade, Boltstorm gauntlet — leads Aggressors"),
      u(6, "Aggressor Squad", 180, "Flamestorm gauntlets, twin power fists"),
      u(1, "Adrax Agatone", 80, "Drakkis, Malleus Noctum — leads Bladeguard"),
      u(6, "Bladeguard Veteran Squad", 160, "Master-crafted power weapons, neo-volkite pistol"),
      u(1, "Librarian", 75, "Temporal Corridor, Force weapon — leads Infernus"),
      u(10, "Infernus Squad", 170, "Pyreblasters"),
      u(1, "Librarian", 80, "Fusillade, Force weapon — leads Sternguard"),
      u(10, "Sternguard Veteran Squad", 190, "Sternguard bolt rifles, 2x heavy bolter, power fist"),
      u(1, "Land Raider Redeemer", 250, "Flamestorm cannons, multi-melta, twin assault cannon"),
      u(1, "Land Raider Redeemer", 250, "Flamestorm cannons, multi-melta, twin assault cannon"),
      u(1, "Land Raider Redeemer", 270, "Flamestorm cannons, multi-melta, twin assault cannon"),
    ],
  },
  {
    id: "manuel", name: "Manuel González", team: "Ñu Team",
    faction: "Necrons", dispo: "Priority Assets",
    summary: { detachment: "Starshatter Arsenal", warlord: "The Silent King", points: 2000, units: 12, enhancements: ["Chrono-impedance Fields (Technomancer)", "Dread Majesty (Overlord)"], secondaries: "" },
    list: [
      u(1, "Technomancer", 105, "Chrono-impedance Fields, Staff of light — leads Canoptek Wraiths"),
      u(6, "Canoptek Wraiths", 220, "Particle casters, vicious claws"),
      u(1, "Overlord", 120, "Dread Majesty, Voidscythe, Resurrection Orb — leads Lychguard"),
      u(10, "Lychguard", 160, "Dispersion shields, hyperphase swords"),
      u(1, "C'tan Shard of the Void Dragon", 345, "Spear of the Void Dragon, Voltaic storm"),
      u(1, "The Silent King", 400, "Warlord, Sceptre of Eternal Glory, 2x Triarchal Menhir"),
      u(1, "Canoptek Reanimator", 70, "Atomiser beams, Reanimator's claws"),
      u(1, "Doomsday Ark", 200, "Doomsday cannon, gauss flayer arrays"),
      u(1, "Doomsday Ark", 200, "Doomsday cannon, gauss flayer arrays"),
      u(5, "Flayed Ones", 55, "Flayer claws"),
      u(5, "Flayed Ones", 55, "Flayer claws"),
      u(3, "Tomb Blades", 70, "Particle beamers, shadowlooms"),
    ],
  },
  {
    id: "manycl", name: "Many CL", team: "Legio Veteris",
    faction: "Space Marines", dispo: "Reconnaissance",
    summary: { detachment: "Ultramarines · Librarius Conclave & Vanguard Spearhead", warlord: "Marneus Calgar", points: 2000, units: 16, enhancements: ["Fusillade (Librarian)", "Temporal Corridor (Librarian in Terminator Armour)"], secondaries: "" },
    list: [
      u(1, "Marneus Calgar in Armour of Antilochus", 140, "Warlord, Gauntlets of Ultramar — leads Assault Terminators"),
      u(5, "Terminator Assault Squad", 175, "Thunder hammers & storm shields, twin lightning claws"),
      u(1, "Uriel Ventris", 95, "Invictus, Sword of Idaeus — leads Company Heroes"),
      u(4, "Company Heroes", 105, "Master-crafted power weapon, master-crafted heavy bolter"),
      u(1, "Librarian", 80, "Fusillade, Force weapon — leads Sternguard"),
      u(1, "Lieutenant", 45, "Master-crafted bolter, Power fist — with Sternguard"),
      u(10, "Sternguard Veteran Squad", 190, "Sternguard bolt rifles, 2x heavy bolter"),
      u(1, "Librarian in Terminator Armour", 90, "Temporal Corridor, Storm bolter — leads Terminators"),
      u(10, "Terminator Squad", 320, "Power fists, storm bolters, 2x cyclone missile launcher"),
      u(1, "Lieutenant with Combi-weapon", 85, "Combi-weapon, Paired combat blades"),
      u(5, "Intercessor Squad", 80, "Bolt rifles, grenade launcher, power fist"),
      u(6, "Inceptor Squad", 240, "Assault bolters"),
      u(3, "Inceptor Squad", 120, "Assault bolters"),
      u(5, "Incursor Squad", 85, "Occulus bolt carbines, haywire mine"),
      u(5, "Incursor Squad", 85, "Occulus bolt carbines, haywire mine"),
      u(5, "Scout Squad", 65, "Sniper rifle, missile launcher, boltguns"),
    ],
  },
  {
    id: "nacho", name: "Nacho Elessarr", team: "Legio Veteris",
    faction: "Necrons", dispo: "Priority Assets",
    summary: { detachment: "Starshatter Arsenal", warlord: "The Silent King", points: 1990, units: 13, enhancements: ["Chrono-impedance Fields (Technomancer)", "Miniaturised Nebuloscope (Lokhust Lord)"], secondaries: "" },
    list: [
      u(1, "Technomancer", 105, "Chrono-impedance Fields, Staff of light — leads Canoptek Wraiths"),
      u(6, "Canoptek Wraiths", 220, "Particle casters, vicious claws"),
      u(1, "Lokhust Lord", 85, "Miniaturised Nebuloscope, Resurrection Orb — leads Heavy Destroyers"),
      u(3, "Lokhust Heavy Destroyers", 150, "Enmitic exterminators"),
      u(1, "C'tan Shard of the Void Dragon", 345, "Spear of the Void Dragon, Voltaic storm"),
      u(1, "Imotekh the Stormlord", 100, "Gauntlet of Fire, Staff of the Destroyer"),
      u(1, "The Silent King", 400, "Warlord, Sceptre of Eternal Glory, 2x Triarchal Menhir"),
      u(3, "Canoptek Scarab Swarms", 40, "Feeder mandibles"),
      u(1, "Canoptek Spyders", 65, "Particle beamers, gloom prism, fabricator claw"),
      u(1, "Doomsday Ark", 200, "Doomsday cannon, gauss flayer arrays"),
      u(1, "Doomsday Ark", 200, "Doomsday cannon, gauss flayer arrays"),
      u(1, "Lokhust Destroyers", 40, "Gauss cannon"),
      u(1, "Lokhust Destroyers", 40, "Gauss cannon"),
    ],
  },
  {
    id: "rafa", name: "Rafa Gonzalez", team: "Freak factory",
    faction: "Imperial Knights", dispo: "Priority Assets",
    summary: { detachment: "Dominus Foebreakers & Gate Warden Lance", warlord: "Knight Castellan", points: 1995, units: 8, enhancements: ["Purgation's Hand (Atrapos)", "Augury Halo (Paladin)"], secondaries: "" },
    list: [
      u(1, "Cerastus Knight Atrapos", 425, "Purgation's Hand, Graviton singularity cannon, Atrapos lascutter"),
      u(1, "Knight Castellan", 400, "Warlord, Volcano lance, Plasma decimator, Shieldbreaker missiles"),
      u(1, "Knight Destrier", 265, "Chastiser gatling cannon, Frag bombard"),
      u(1, "Knight Paladin", 395, "Augury Halo, Rapid-fire battle cannon, Reaper chainsword"),
      u(1, "Armiger Warglaive", 140, "Thermal spear, Reaper chain-cleaver"),
      u(1, "Armiger Warglaive", 140, "Thermal spear, Reaper chain-cleaver, meltagun"),
      u(1, "Sisters of Battle Immolator (allied)", 115, "Immolation flamers, heavy bolter"),
      u(10, "Sisters of Battle Squad (allied)", 115, "Boltguns, heavy flamer, Simulacrum Imperialis"),
    ],
  },
  {
    id: "ruben", name: "Ruben Martín", team: "Freak factory",
    faction: "T'au Empire", dispo: "Purge the Foe",
    summary: { detachment: "Advanced Acquisition Cadre & Retaliation Cadre", warlord: "Commander Farsight", points: 2000, units: 18, enhancements: ["Starflare Ignition System (Commander in Enforcer)"], secondaries: "" },
    list: [
      u(1, "Commander Farsight", 80, "Warlord, Dawn Blade, plasma rifle — leads Sunforge"),
      u(3, "Crisis Sunforge Battlesuits", 125, "Fusion blasters, shield drones"),
      u(1, "Commander in Enforcer Battlesuit", 100, "Starflare Ignition System, 4x Missile pod — leads Fireknife"),
      u(3, "Crisis Fireknife Battlesuits", 130, "Missile pods, gun & shield drones"),
      u(1, "Commander in Coldstar Battlesuit", 95, "High-output burst cannon, cyclic ion blaster — leads Starscythe"),
      u(3, "Crisis Starscythe Battlesuits", 90, "Burst cannons, drones"),
      u(1, "Commander in Coldstar Battlesuit", 95, "High-output burst cannon, cyclic ion blaster — leads Starscythe"),
      u(3, "Crisis Starscythe Battlesuits", 90, "Burst cannons, drones"),
      u(2, "The Twin Lance", 205, "Ri'Lantar & Ri'Locai — fusion eliminator, ion scattercannon"),
      u(3, "Crisis Fireknife Battlesuits", 100, "Plasma rifles, gun & shield drones"),
      u(10, "Pathfinder Team", 80, "3x Rail rifle, recon drone, marker drone"),
      u(10, "Pathfinder Team", 80, "3x Rail rifle, grav-inhibitor drone"),
      u(1, "Piranhas", 65, "Fusion blaster, seeker missiles"),
      u(1, "Piranhas", 65, "Fusion blaster, seeker missiles"),
      u(1, "Riptide Battlesuit", 200, "Ion accelerator, twin fusion blaster, missile drones"),
      u(1, "Riptide Battlesuit", 200, "Ion accelerator, twin fusion blaster, missile drones"),
      u(5, "Stealth Battlesuits", 100, "Burst cannons, fusion blasters, homing beacon"),
      u(5, "Stealth Battlesuits", 100, "Burst cannons, fusion blasters, homing beacon"),
    ],
  },
  {
    id: "sergio", name: "Sergio Galán", team: "Legio Veteris",
    faction: "Orks", dispo: "Take and Hold",
    summary: { detachment: "War Horde", warlord: "Ghazghkull Thraka", points: 2000, units: 18, enhancements: [], secondaries: "" },
    list: [
      u(1, "Ghazghkull Thraka", 235, "Warlord, Gork's Klaw, Mork's Roar, Makari — leads Meganobz"),
      u(5, "Meganobz", 150, "Killsaws, power klaws"),
      u(1, "Beastboss", 80, "Beast Snagga klaw, Beastchoppa — leads Beast Snaggas"),
      u(10, "Beast Snagga Boyz", 90, "Choppas, sluggas, power snappa"),
      u(1, "Beastboss", 80, "Beast Snagga klaw, Beastchoppa — leads Beast Snaggas"),
      u(10, "Beast Snagga Boyz", 90, "Choppas, sluggas, power snappa"),
      u(1, "Mozrog Skragbad", 125, "Big Chompa's jaws, Gutrippa — leads Squighog Boyz"),
      u(4, "Squighog Boyz", 140, "Squig jaws, stikkas, bomb squig"),
      u(1, "Boss Snikrot", 75, "Mork's Teeth, slugga"),
      u(1, "Wazdakka Gutsmek", 175, "Psyko-gatler, grabba dragga"),
      u(1, "Big Mek Dakkarig", 100, "Blitzkannon, rokkit launcha"),
      u(1, "Big Mek Dakkarig", 100, "Blitzkannon, rokkit launcha"),
      u(11, "Gretchin", 45, "Grot blastas, runtherd"),
      u(11, "Gretchin", 45, "Grot blastas, runtherd"),
      u(1, "Kill Rig", 145, "Stikka kannon, 'eavy lobba, wurrtower"),
      u(1, "Kill Rig", 145, "Stikka kannon, 'eavy lobba, wurrtower"),
      u(10, "Kommandos", 120, "Choppas, sluggas"),
      u(3, "Warbikers", 60, "Twin dakkaguns, power klaw"),
    ],
  },
  {
    id: "angel-g", name: "Ángel García Domínguez", team: "Legio Veteris",
    faction: "World Eaters", dispo: "Purge the Foe",
    summary: { detachment: "Brazen Engines & Possessed Slaughterband", warlord: "Daemon Prince of Khorne", points: 1980, units: 11, enhancements: ["Killing Clarity (Slaughterbound)", "Frenzied Focus (Slaughterbound)"], secondaries: "" },
    list: [
      u(1, "Slaughterbound", 115, "Killing Clarity, Lacerator & daemonic claw — leads Eightbound"),
      u(6, "Eightbound", 270, "Chainblades"),
      u(1, "Slaughterbound", 120, "Frenzied Focus, Lacerator & daemonic claw — leads Exalted Eightbound"),
      u(6, "Exalted Eightbound", 280, "Chainblades"),
      u(1, "Daemon Prince of Khorne", 200, "Warlord, Hellforged weapons, Infernal cannon"),
      u(1, "Defiler", 280, "Ectoplasma destructor, Hades lascannon, electroscourge"),
      u(1, "Defiler", 310, "Ectoplasma destructor, Hades lascannon, electroscourge"),
      u(3, "Eightbound", 135, "Chainblades"),
      u(3, "Exalted Eightbound", 140, "Chainblades"),
      u(10, "Jakhals", 65, "Autopistols, chainblades, Icon of Khorne"),
      u(10, "Jakhals", 65, "Autopistols, chainblades, skullsmasher"),
    ],
  },
];
