// Málaga Open — roster data. Fake lists except Miguel Puerta Rodriguez (real).
// Replace / extend freely: each player = { id, name, team, faction, dispo, summary, list }

export const FACTION_COLORS = {
  "Necrons": "#30A46C",
  "Blood Angels": "#E5484D",
  "Space Marines": "#0A84FF",
  "Chaos Space Marines": "#8E4EC6",
  "Adeptus Mechanicus": "#E5484D",
  "Emperor's Children": "#D6409F",
  "Astra Militarum": "#8F8B5C",
  "Imperial Knights": "#F76B15",
  "T'au Empire": "#00A2C7",
  "Orks": "#46A758",
  "World Eaters": "#DC3E42",
};

export const MAP_POOLS = {
  "Take and Hold": [
    { layout: "Layout 2", deployment: "Hammer & Anvil" },
    { layout: "Layout 4", deployment: "Search & Destroy" },
    { layout: "Layout 6", deployment: "Crucible of Battle" },
  ],
  "Purge the Foe": [
    { layout: "Layout 1", deployment: "Dawn of War" },
    { layout: "Layout 3", deployment: "Sweeping Engagement" },
    { layout: "Layout 8", deployment: "Hammer & Anvil" },
  ],
  "Priority Assets": [
    { layout: "Layout 2", deployment: "Crucible of Battle" },
    { layout: "Layout 5", deployment: "Dawn of War" },
    { layout: "Layout 7", deployment: "Search & Destroy" },
  ],
  "Reconnaissance": [
    { layout: "Layout 3", deployment: "Hammer & Anvil" },
    { layout: "Layout 6", deployment: "Sweeping Engagement" },
    { layout: "Layout 8", deployment: "Tipping Point" },
  ],
  "Disruption": [
    { layout: "Layout 1", deployment: "Crucible of Battle" },
    { layout: "Layout 4", deployment: "Dawn of War" },
    { layout: "Layout 7", deployment: "Tipping Point" },
  ],
};

// Primary mission = MISSION_MATRIX[yourDispo][opponentDispo] (GDM 2026, 11th ed.)
export const MISSION_MATRIX = {
  "Take and Hold": {
    "Take and Hold": "Battlefield Dominance",
    "Purge the Foe": "Immovable Object",
    "Disruption": "Determined Acquisition",
    "Reconnaissance": "Purge and Secure",
    "Priority Assets": "Inescapable Dominion",
  },
  "Purge the Foe": {
    "Take and Hold": "Unstoppable Force",
    "Purge the Foe": "Meatgrinder",
    "Disruption": "Punishment",
    "Reconnaissance": "Consecrate",
    "Priority Assets": "Destroyer's Wrath",
  },
  "Disruption": {
    "Take and Hold": "Death Trap",
    "Purge the Foe": "Delaying Action",
    "Disruption": "Outmanoeuvre",
    "Reconnaissance": "Smoke and Mirrors",
    "Priority Assets": "Locate and Deny",
  },
  "Reconnaissance": {
    "Take and Hold": "Reconnaissance Sweep",
    "Purge the Foe": "Triangulation",
    "Disruption": "Surveil the Foe",
    "Reconnaissance": "Gather Intel",
    "Priority Assets": "Search and Scour",
  },
  "Priority Assets": {
    "Take and Hold": "Secure Asset",
    "Purge the Foe": "Vital Link",
    "Disruption": "Extract Relic",
    "Reconnaissance": "Vanguard Operation",
    "Priority Assets": "Sabotage",
  },
};

const u = (qty, name, pts, gear) => ({ qty, name, pts, gear });

export const PLAYERS = [
  {
    id: "dimitri", name: "Dimitri Farber Garcia", team: "Legio Veteris",
    faction: "Space Marines", dispo: "Take and Hold",
    summary: { detachment: "Gladius Task Force", warlord: "Marneus Calgar", points: 2000, units: 14, enhancements: ["Artificer Armour (Captain)"], secondaries: "Bring It Down: 2x2 — Assassination: 5 Characters" },
    list: [
      u(1, "Marneus Calgar", 185, "Warlord, Gauntlets of Ultramar, Victrix Honour Guard"),
      u(1, "Captain in Gravis Armour", 105, "Artificer Armour, Boltstorm gauntlet, Power fist"),
      u(1, "Apothecary Biologis", 70, "Absolver bolt pistol"),
      u(1, "Lieutenant", 65, "Master-crafted bolter, Power weapon"),
      u(5, "Intercessor Squad", 80, "Bolt rifles, Astartes grenade launcher"),
      u(5, "Intercessor Squad", 80, "Bolt rifles, Astartes grenade launcher"),
      u(10, "Assault Intercessors", 150, "Astartes chainswords, Heavy bolt pistols"),
      u(6, "Aggressor Squad", 240, "Flamestorm gauntlets"),
      u(3, "Eradicator Squad", 100, "Melta rifles, Multi-melta"),
      u(3, "Eradicator Squad", 100, "Melta rifles, Multi-melta"),
      u(1, "Repulsor Executioner", 220, "Heavy laser destroyer, Icarus rocket pod"),
      u(1, "Gladiator Lancer", 160, "Laser destroyer, Fragstorm grenade launchers"),
      u(5, "Infernus Squad", 90, "Pyreblasters"),
      u(1, "Impulsor", 80, "Bellicatus missile array, Shield dome"),
    ],
  },
  {
    id: "miguel", name: "Miguel Puerta Rodriguez", team: "LEGIO IX HISPANA",
    faction: "Necrons", dispo: "Take and Hold",
    summary: {
      detachment: "Awakened Dynasty (Command Protocols)", warlord: "Imotekh the Stormlord", points: 2000, units: 16,
      enhancements: ["Nether-realm Casket (Royal Warden)", "Enaegic Dermal Bond (Skorpekh Lord)"],
      secondaries: "Bring It Down: (2x2) + (1x4) — Assassination: 9 Characters — Cull The Horde: 1x5 (before leaders attached)",
    },
    list: [
      u(1, "C'tan Shard of the Deceiver", 330, "Cosmic insanity, Golden fists"),
      u(1, "Catacomb Command Barge", 120, "Resurrection orb, Gauss cannon, Overlord's blade"),
      u(1, "Illuminor Szeras", 175, "Eldritch lance, Impaling legs"),
      u(1, "Imotekh the Stormlord", 100, "Warlord, Gauntlet of Fire, Staff of the Destroyer"),
      u(1, "Orikan the Diviner", 90, "Staff of Tomorrow — leads Necron Warriors"),
      u(1, "Overlord", 90, "Resurrection orb, Voidscythe"),
      u(1, "Royal Warden", 90, "Relic gauss blaster — Nether-realm Casket (+20) — leads Necron Warriors"),
      u(1, "Skorpekh Lord", 150, "Enmitic annihilator, Flensing claw, Hyperphase harvester — Enaegic Dermal Bond (+30)"),
      u(1, "Technomancer", 80, "Staff of light — leads Canoptek Wraiths"),
      u(20, "Necron Warriors", 190, "Close combat weapons, Gauss reapers"),
      u(1, "Canoptek Reanimator", 70, "2x Atomiser beam, Reanimator's claws"),
      u(2, "Canoptek Tomb Crawlers", 50, "Claws, Twin gauss reaper / Dimensional isolator — moves with Warriors"),
      u(6, "Canoptek Wraiths", 220, "Particle casters, Vicious claws"),
      u(5, "Flayed Ones", 55, "Flayer claws"),
      u(10, "Lychguard", 160, "Dispersion shields, Hyperphase swords"),
      u(3, "Ophydian Destroyers", 80, "Plasmacyte, Ophydian hyperphase weapons"),
    ],
  },
  {
    id: "angel-c", name: "Angel Cañamero", team: "El Ordo Autista",
    faction: "Blood Angels", dispo: "Purge the Foe",
    summary: { detachment: "Liberator Assault Group", warlord: "Commander Dante", points: 2000, units: 13, enhancements: ["Icon of the Angel (Captain)"], secondaries: "Assassination: 4 Characters" },
    list: [
      u(1, "Commander Dante", 130, "Warlord, Axe Mortalis, Perdition pistol"),
      u(1, "Captain with Jump Pack", 95, "Icon of the Angel, Thunder hammer"),
      u(1, "Sanguinary Priest", 85, "Blood chalice, Power fist"),
      u(1, "Lemartes", 110, "Guardian of the Lost"),
      u(10, "Death Company w/ Jump Packs", 260, "Chainswords, 2x Thunder hammer"),
      u(10, "Assault Intercessors", 150, "Astartes chainswords"),
      u(5, "Jump Pack Intercessors", 90, "Bolt pistols, Chainswords"),
      u(5, "Jump Pack Intercessors", 90, "Bolt pistols, Chainswords"),
      u(6, "Sanguinary Guard", 280, "Encarmine blades, Angelus boltguns"),
      u(3, "Outrider Squad", 80, "Twin bolt rifles"),
      u(1, "Storm Speeder Thunderstrike", 150, "Stormfury missiles"),
      u(1, "Gladiator Lancer", 160, "Laser destroyer"),
      u(5, "Scout Squad", 70, "Sniper rifle, Missile launcher"),
    ],
  },
  {
    id: "boris", name: "Boris Hollander", team: "—",
    faction: "Chaos Space Marines", dispo: "Disruption",
    summary: { detachment: "Veterans of the Long War", warlord: "Abaddon the Despoiler", points: 2000, units: 12, enhancements: ["Liber Hereticus (Sorcerer)"], secondaries: "Bring It Down: 1x4 — Assassination: 4 Characters" },
    list: [
      u(1, "Abaddon the Despoiler", 310, "Warlord, Talon of Horus, Drach'nyen"),
      u(1, "Sorcerer in Terminator Armour", 95, "Liber Hereticus, Force weapon"),
      u(1, "Master of Possession", 75, "Staff of possession"),
      u(10, "Chaos Terminators", 380, "Combi-weapons, Power fists, Reaper autocannon"),
      u(10, "Legionaries", 160, "Bolters, Lascannon, Icon"),
      u(10, "Cultist Mob", 50, "Autopistols, Brutal assault weapons"),
      u(10, "Cultist Mob", 50, "Autopistols, Brutal assault weapons"),
      u(5, "Possessed", 140, "Hideous mutations"),
      u(5, "Possessed", 140, "Hideous mutations"),
      u(1, "Forgefiend", 170, "3x Ectoplasma cannon"),
      u(1, "Rhino", 75, "Combi-bolter, Havoc launcher"),
      u(1, "Land Raider", 240, "Twin lascannons, Heavy bolters"),
    ],
  },
  {
    id: "capitan", name: "Capitán Mechero", team: "El Ordo Autista",
    faction: "Adeptus Mechanicus", dispo: "Priority Assets",
    summary: { detachment: "Skitarii Hunter Cohort", warlord: "Tech-Priest Manipulus", points: 2000, units: 15, enhancements: ["Cognitive Reinforcement (Marshal)"], secondaries: "Cull The Horde: 2x10" },
    list: [
      u(1, "Tech-Priest Manipulus", 60, "Warlord, Transonic cannon"),
      u(1, "Skitarii Marshal", 55, "Cognitive Reinforcement, Control stave"),
      u(1, "Technoarcheologist", 45, "Servo-arc claw"),
      u(10, "Skitarii Rangers", 85, "Galvanic rifles, 2x Transuranic arquebus"),
      u(10, "Skitarii Rangers", 85, "Galvanic rifles, 2x Transuranic arquebus"),
      u(10, "Skitarii Vanguard", 95, "Radium carbines, 3x Plasma caliver"),
      u(10, "Skitarii Vanguard", 95, "Radium carbines, 3x Plasma caliver"),
      u(5, "Sicarian Infiltrators", 70, "Flechette blasters, Taser goads"),
      u(5, "Sicarian Ruststalkers", 75, "Transonic razors"),
      u(3, "Kataphron Breachers", 160, "Heavy arc rifles"),
      u(3, "Kataphron Breachers", 160, "Heavy arc rifles"),
      u(1, "Onager Dunecrawler", 155, "Icarus array"),
      u(1, "Skorpius Disintegrator", 175, "Belleros energy cannon"),
      u(2, "Ironstrider Ballistarii", 150, "Twin cognis lascannons"),
      u(1, "Archaeopter Fusilave", 160, "Bombs, Cognis heavy stubbers"),
    ],
  },
  {
    id: "coronel", name: "Coronel T.H.", team: "El Ordo Autista",
    faction: "Necrons", dispo: "Reconnaissance",
    summary: { detachment: "Canoptek Court", warlord: "Technomancer", points: 2000, units: 13, enhancements: ["Metalodermal Tesla Weave (Technomancer)"], secondaries: "Bring It Down: 3x4" },
    list: [
      u(1, "Technomancer", 105, "Warlord, Metalodermal Tesla Weave, Staff of light"),
      u(1, "Hexmark Destroyer", 75, "Enmitic disintegrator pistols"),
      u(1, "Plasmancer", 60, "Plasmic lance"),
      u(20, "Necron Warriors", 190, "Gauss flayers"),
      u(10, "Immortals", 150, "Tesla carbines"),
      u(10, "Immortals", 150, "Tesla carbines"),
      u(6, "Canoptek Wraiths", 220, "Particle casters, Vicious claws"),
      u(6, "Canoptek Scarab Swarms", 80, "Feeder mandibles"),
      u(3, "Canoptek Spyders", 225, "Fabricator claw arrays"),
      u(1, "Canoptek Doomstalker", 145, "Doomsday blaster"),
      u(1, "Canoptek Doomstalker", 145, "Doomsday blaster"),
      u(1, "Monolith", 400, "Gauss flux arcs, Particle whip"),
      u(2, "Cryptothralls", 55, "Scouring eyes"),
    ],
  },
  {
    id: "forthemperor", name: "For the Emperor", team: "1UP",
    faction: "Space Marines", dispo: "Purge the Foe",
    summary: { detachment: "Ironstorm Spearhead", warlord: "Techmarine", points: 2000, units: 11, enhancements: ["The Flesh is Weak (Techmarine)"], secondaries: "Bring It Down: 5x4" },
    list: [
      u(1, "Techmarine", 85, "Warlord, The Flesh is Weak, Forge bolter"),
      u(1, "Lieutenant with Combi-weapon", 70, "Combi-weapon, Paired combat blades"),
      u(5, "Infiltrator Squad", 100, "Marksman bolt carbines, Helix gauntlet"),
      u(5, "Infiltrator Squad", 100, "Marksman bolt carbines, Helix gauntlet"),
      u(5, "Scout Squad", 70, "Sniper rifle, Missile launcher"),
      u(1, "Repulsor Executioner", 220, "Heavy laser destroyer"),
      u(1, "Repulsor Executioner", 220, "Heavy laser destroyer"),
      u(1, "Gladiator Lancer", 160, "Laser destroyer"),
      u(1, "Gladiator Lancer", 160, "Laser destroyer"),
      u(1, "Redemptor Dreadnought", 210, "Macro plasma incinerator"),
      u(1, "Brutalis Dreadnought", 160, "Brutalis fists, Multi-meltas"),
    ],
  },
  {
    id: "francisco", name: "Francisco Javier Domínguez Granado", team: "Legio Veteris",
    faction: "Space Marines", dispo: "Purge the Foe",
    summary: { detachment: "Stormlance Task Force", warlord: "Chaplain on Bike", points: 2000, units: 12, enhancements: ["Hunter's Instincts (Chaplain)"], secondaries: "Assassination: 3 Characters" },
    list: [
      u(1, "Chaplain on Bike", 105, "Warlord, Hunter's Instincts, Crozius arcanum"),
      u(1, "Captain on Bike", 90, "Power fist, Plasma pistol"),
      u(6, "Outrider Squad", 160, "Twin bolt rifles"),
      u(6, "Outrider Squad", 160, "Twin bolt rifles"),
      u(3, "Outrider Squad", 80, "Twin bolt rifles"),
      u(10, "Assault Intercessors", 150, "Chainswords"),
      u(5, "Scout Squad", 70, "Sniper rifle"),
      u(1, "Storm Speeder Hailstrike", 110, "Fragstorm grenade launchers"),
      u(1, "Storm Speeder Thunderstrike", 150, "Stormfury missiles"),
      u(3, "Vulkite Contemptors (proxy)", 355, "—"),
      u(1, "Gladiator Valiant", 160, "Twin laser destroyer"),
      u(1, "Impulsor", 80, "Shield dome"),
    ],
  },
  {
    id: "israel", name: "Israel Caballeros del Caos", team: "Legio Veteris",
    faction: "Emperor's Children", dispo: "Priority Assets",
    summary: { detachment: "Peerless Bladesmen", warlord: "Lucius the Eternal", points: 2000, units: 12, enhancements: ["Rapacious Ego (Lord Exultant)"], secondaries: "Assassination: 4 Characters" },
    list: [
      u(1, "Lucius the Eternal", 140, "Warlord, Lash of Torment"),
      u(1, "Lord Exultant", 105, "Rapacious Ego, Phoenix power spear"),
      u(1, "Lord Kakophonist", 75, "Screech-hammer"),
      u(10, "Tormentors", 155, "Bolters, Sonic weapons"),
      u(10, "Tormentors", 155, "Bolters, Sonic weapons"),
      u(10, "Noise Marines", 250, "Sonic blasters, Blastmaster"),
      u(5, "Flawless Blades", 130, "Duellist blades"),
      u(5, "Flawless Blades", 130, "Duellist blades"),
      u(3, "Exalted Daemonettes (allied)", 85, "Piercing claws"),
      u(1, "Rhino", 75, "Combi-bolter"),
      u(1, "Rhino", 75, "Combi-bolter"),
      u(1, "Land Raider", 240, "Twin lascannons"),
    ],
  },
  {
    id: "josemanuel", name: "Jose Manuel Aguilar Rodriguez", team: "LEGIO IX HISPANA",
    faction: "Astra Militarum", dispo: "Purge the Foe",
    summary: { detachment: "Combined Regiment", warlord: "Lord Solar Leontus", points: 2000, units: 16, enhancements: ["Grand Strategist (Command Squad)"], secondaries: "Cull The Horde: 3x10" },
    list: [
      u(1, "Lord Solar Leontus", 150, "Warlord, Sol's Righteous Gaze"),
      u(1, "Cadian Command Squad", 65, "Grand Strategist, Regimental standard"),
      u(1, "Platoon Command Squad", 60, "Master vox"),
      u(20, "Cadian Shock Troops", 130, "Lasguns, 2x Plasma gun"),
      u(20, "Cadian Shock Troops", 130, "Lasguns, 2x Plasma gun"),
      u(10, "Kasrkin", 100, "Hot-shot lasguns, 2x Melta"),
      u(3, "Field Ordnance Battery", 110, "Malleus rocket launchers"),
      u(1, "Basilisk", 140, "Earthshaker cannon"),
      u(1, "Basilisk", 140, "Earthshaker cannon"),
      u(1, "Leman Russ Vanquisher", 145, "Vanquisher battle cannon"),
      u(1, "Leman Russ Demolisher", 165, "Demolisher battle cannon"),
      u(1, "Rogal Dorn Battle Tank", 240, "Twin battle cannon"),
      u(1, "Chimera", 70, "Multi-laser"),
      u(1, "Chimera", 70, "Multi-laser"),
      u(1, "Scout Sentinel", 55, "Lascannon"),
      u(3, "Bullgryn Squad", 100, "Slabshields, Grenadier gauntlets"),
    ],
  },
  {
    id: "juanignacio", name: "Juan Ignacio Dacrov", team: "—",
    faction: "Space Marines", dispo: "Priority Assets",
    summary: { detachment: "Firestorm Assault Force", warlord: "Vulkan He'stan", points: 2000, units: 12, enhancements: ["Champion of Humanity (Captain)"], secondaries: "Assassination: 4 Characters" },
    list: [
      u(1, "Vulkan He'stan", 100, "Warlord, Spear of Vulkan"),
      u(1, "Captain in Gravis Armour", 100, "Champion of Humanity"),
      u(1, "Apothecary Biologis", 70, "Absolver bolt pistol"),
      u(6, "Aggressor Squad", 240, "Flamestorm gauntlets"),
      u(6, "Aggressor Squad", 240, "Flamestorm gauntlets"),
      u(10, "Infernus Squad", 180, "Pyreblasters"),
      u(5, "Infernus Squad", 90, "Pyreblasters"),
      u(3, "Eradicator Squad", 100, "Melta rifles"),
      u(3, "Eradicator Squad", 100, "Melta rifles"),
      u(1, "Land Raider Redeemer", 285, "Flamestorm cannons"),
      u(1, "Repulsor", 180, "Las-talon"),
      u(5, "Scout Squad", 70, "Sniper rifle"),
    ],
  },
  {
    id: "juanjose", name: "Juan José Wu", team: "Gondor 40K",
    faction: "Blood Angels", dispo: "Take and Hold",
    summary: { detachment: "The Angelic Host", warlord: "The Sanguinor", points: 2000, units: 12, enhancements: ["Artisan of War (Sanguinary Priest)"], secondaries: "Assassination: 5 Characters" },
    list: [
      u(1, "The Sanguinor", 140, "Warlord, Encarmine broadsword"),
      u(1, "Astorath", 105, "The Executioner's Axe"),
      u(1, "Sanguinary Priest w/ Jump Pack", 100, "Artisan of War"),
      u(10, "Death Company w/ Jump Packs", 260, "2x Power fist, Chainswords"),
      u(10, "Death Company w/ Jump Packs", 260, "2x Power fist, Chainswords"),
      u(6, "Sanguinary Guard", 280, "Encarmine blades"),
      u(6, "Sanguinary Guard", 280, "Encarmine blades"),
      u(5, "Jump Pack Intercessors", 90, "Chainswords"),
      u(5, "Jump Pack Intercessors", 90, "Chainswords"),
      u(5, "Scout Squad", 70, "Sniper rifle"),
      u(5, "Scout Squad", 70, "Sniper rifle"),
      u(1, "Storm Speeder Thunderstrike", 150, "Stormfury missiles"),
    ],
  },
  {
    id: "juanma", name: "Juanma Melilla", team: "Diario de un Recluta",
    faction: "Space Marines", dispo: "Purge the Foe",
    summary: { detachment: "Vanguard Spearhead", warlord: "Captain with Phobos Armour", points: 2000, units: 13, enhancements: ["Ghostweave Cloak (Librarian)"], secondaries: "Assassination: 3 Characters" },
    list: [
      u(1, "Captain in Phobos Armour", 80, "Warlord, Instigator bolt carbine"),
      u(1, "Librarian in Phobos Armour", 100, "Ghostweave Cloak"),
      u(1, "Lieutenant in Reiver Armour", 55, "Special-issue bolt pistol"),
      u(10, "Infiltrator Squad", 200, "Helix gauntlet, Comms array"),
      u(10, "Infiltrator Squad", 200, "Helix gauntlet, Comms array"),
      u(5, "Incursor Squad", 80, "Occulus bolt carbines"),
      u(5, "Incursor Squad", 80, "Occulus bolt carbines"),
      u(3, "Eliminator Squad", 85, "Bolt sniper rifles"),
      u(3, "Eliminator Squad", 85, "Bolt sniper rifles"),
      u(5, "Reiver Squad", 80, "Combat knives, Grav-chutes"),
      u(1, "Gladiator Lancer", 160, "Laser destroyer"),
      u(1, "Gladiator Lancer", 160, "Laser destroyer"),
      u(1, "Storm Speeder Hammerstrike", 145, "Hammerstrike missile launcher"),
    ],
  },
  {
    id: "manuel", name: "Manuel González", team: "Ñu Team",
    faction: "Necrons", dispo: "Priority Assets",
    summary: { detachment: "Hypercrypt Legion", warlord: "The Silent King", points: 2000, units: 11, enhancements: ["Osteoclave Fulcrum (Overlord)"], secondaries: "Bring It Down: 1x8 + 2x4" },
    list: [
      u(1, "The Silent King", 420, "Warlord, Sceptre of Eternal Glory"),
      u(1, "Overlord with Translocation Shroud", 105, "Osteoclave Fulcrum, Resurrection orb"),
      u(1, "Chronomancer", 65, "Chronotendrils"),
      u(10, "Immortals", 150, "Gauss blasters"),
      u(10, "Immortals", 150, "Gauss blasters"),
      u(6, "Canoptek Wraiths", 220, "Vicious claws"),
      u(1, "Monolith", 400, "Particle whip, Gauss flux arcs"),
      u(1, "Doomsday Ark", 200, "Doomsday cannon"),
      u(3, "Lokhust Heavy Destroyers", 165, "Gauss destructors"),
      u(2, "Cryptothralls", 55, "Scouring eyes"),
      u(1, "Canoptek Doomstalker", 145, "Doomsday blaster"),
    ],
  },
  {
    id: "manycl", name: "Many CL", team: "Legio Veteris",
    faction: "Space Marines", dispo: "Reconnaissance",
    summary: { detachment: "1st Company Task Force", warlord: "Captain in Terminator Armour", points: 2000, units: 11, enhancements: ["Iron Resolve (Captain)"], secondaries: "Bring It Down: 2x4" },
    list: [
      u(1, "Captain in Terminator Armour", 105, "Warlord, Iron Resolve, Relic fist"),
      u(1, "Ancient in Terminator Armour", 75, "Company standard"),
      u(1, "Chaplain in Terminator Armour", 75, "Crozius arcanum"),
      u(10, "Terminator Squad", 340, "Power fists, 2x Cyclone missile launcher"),
      u(5, "Terminator Assault Squad", 180, "Thunder hammers, Storm shields"),
      u(5, "Terminator Assault Squad", 180, "Thunder hammers, Storm shields"),
      u(5, "Sternguard Veteran Squad", 90, "Sternguard bolt rifles"),
      u(5, "Sternguard Veteran Squad", 90, "Sternguard bolt rifles"),
      u(1, "Land Raider Crusader", 220, "Hurricane bolters"),
      u(1, "Redemptor Dreadnought", 210, "Macro plasma incinerator"),
      u(1, "Repulsor Executioner", 220, "Heavy laser destroyer"),
    ],
  },
  {
    id: "nacho", name: "Nacho Elessarr", team: "Legio Veteris",
    faction: "Necrons", dispo: "Priority Assets",
    summary: { detachment: "Obeisance Phalanx", warlord: "Overlord", points: 2000, units: 12, enhancements: ["Eternal Madness (Overlord)"], secondaries: "Bring It Down: 2x4 — Assassination: 5 Characters" },
    list: [
      u(1, "Overlord", 115, "Warlord, Eternal Madness, Voidscythe"),
      u(1, "Anrakyr the Traveller", 90, "Warscythe, Tachyon arrow"),
      u(1, "Royal Warden", 50, "Relic gauss blaster"),
      u(1, "Skorpekh Lord", 90, "Flensing claw"),
      u(1, "Technomancer", 80, "Staff of light"),
      u(10, "Lychguard", 160, "Dispersion shields"),
      u(10, "Lychguard", 160, "Dispersion shields"),
      u(6, "Skorpekh Destroyers", 210, "Skorpekh hyperphase weapons"),
      u(20, "Necron Warriors", 190, "Gauss reapers"),
      u(3, "Lokhust Heavy Destroyers", 165, "Gauss destructors"),
      u(1, "Annihilation Barge", 110, "Twin tesla destructor"),
      u(1, "Ghost Ark", 115, "Gauss flayer arrays"),
    ],
  },
  {
    id: "rafa", name: "Rafa Gonzalez", team: "Freak factory",
    faction: "Imperial Knights", dispo: "Priority Assets",
    summary: { detachment: "Noble Lance", warlord: "Knight Valiant", points: 2000, units: 8, enhancements: ["Revered Knight (Valiant)"], secondaries: "Bring It Down: 4x8" },
    list: [
      u(1, "Knight Valiant", 495, "Warlord, Revered Knight, Thundercoil harpoon"),
      u(1, "Knight Crusader", 445, "Rapid-fire battle cannon, Thermal cannon"),
      u(1, "Armiger Helverin", 145, "Armiger autocannons"),
      u(1, "Armiger Helverin", 145, "Armiger autocannons"),
      u(1, "Armiger Warglaive", 140, "Thermal spear, Reaper chain-cleaver"),
      u(1, "Armiger Warglaive", 140, "Thermal spear, Reaper chain-cleaver"),
      u(1, "Armiger Warglaive", 140, "Thermal spear, Reaper chain-cleaver"),
      u(1, "Knight Preceptor", 350, "Las-impulsor"),
    ],
  },
  {
    id: "ruben", name: "Ruben Martín", team: "Freak factory",
    faction: "T'au Empire", dispo: "Purge the Foe",
    summary: { detachment: "Kauyon", warlord: "Commander Shadowsun", points: 2000, units: 13, enhancements: ["Through Unity, Devastation (Coldstar)"], secondaries: "Bring It Down: 3x4" },
    list: [
      u(1, "Commander Shadowsun", 100, "Warlord, High-energy fusion blasters"),
      u(1, "Commander in Coldstar Battlesuit", 115, "Through Unity Devastation, 4x Fusion blaster"),
      u(1, "Ethereal", 50, "Honour stave, Hover drone"),
      u(3, "Crisis Fireknife Battlesuits", 130, "Plasma rifles, Missile pods"),
      u(3, "Crisis Sunforge Battlesuits", 150, "Fusion blasters"),
      u(3, "Crisis Sunforge Battlesuits", 150, "Fusion blasters"),
      u(10, "Breacher Team", 100, "Pulse blasters, Support turret"),
      u(10, "Breacher Team", 100, "Pulse blasters, Support turret"),
      u(1, "Riptide Battlesuit", 190, "Ion accelerator"),
      u(1, "Hammerhead Gunship", 145, "Railgun"),
      u(1, "Hammerhead Gunship", 145, "Railgun"),
      u(2, "Devilfish", 170, "Burst cannons"),
      u(4, "Stealth Battlesuits", 60, "Burst cannons, Fusion blaster"),
    ],
  },
  {
    id: "sergio", name: "Sergio Galán", team: "Legio Veteris",
    faction: "Orks", dispo: "Take and Hold",
    summary: { detachment: "War Horde", warlord: "Ghazghkull Thraka", points: 2000, units: 13, enhancements: ["Headwoppa's Killchoppa (Warboss)"], secondaries: "Cull The Horde: 2x20" },
    list: [
      u(1, "Ghazghkull Thraka", 235, "Warlord, Gork's Klaw, Makari"),
      u(1, "Warboss", 90, "Headwoppa's Killchoppa"),
      u(1, "Weirdboy", 55, "Weirdboy staff"),
      u(1, "Painboy", 70, "'Urty syringe"),
      u(20, "Boyz", 170, "Choppas, Sluggas"),
      u(20, "Boyz", 170, "Choppas, Sluggas"),
      u(10, "Nobz", 210, "Power klaws"),
      u(5, "Meganobz", 175, "Power klaws, Twin shootas"),
      u(3, "Deffkoptas", 100, "Rokkit launchas"),
      u(1, "Battlewagon", 160, "'Ard case, Deff rolla"),
      u(1, "Trukk", 65, "Big shoota"),
      u(1, "Deff Dread", 130, "4x Dread klaw"),
      u(10, "Gretchin", 40, "Grot blastas"),
    ],
  },
  {
    id: "angel-g", name: "Ángel García Domínguez", team: "Legio Veteris",
    faction: "World Eaters", dispo: "Purge the Foe",
    summary: { detachment: "Berzerker Warband", warlord: "Angron", points: 2000, units: 11, enhancements: ["Berzerker Glaive (Master of Executions)"], secondaries: "Bring It Down: 1x8 — Assassination: 4 Characters" },
    list: [
      u(1, "Angron", 415, "Warlord, Samni'arius and Spinegrinder"),
      u(1, "Kharn the Betrayer", 100, "Gorechild"),
      u(1, "Master of Executions", 125, "Berzerker Glaive, Axe of dismemberment"),
      u(1, "Lord Invocatus", 140, "Coward's Bane"),
      u(10, "Khorne Berzerkers", 190, "Chainblades, 2x Plasma pistol"),
      u(10, "Khorne Berzerkers", 190, "Chainblades, 2x Plasma pistol"),
      u(10, "Jakhals", 70, "Autopistols, Dishonoured icon"),
      u(3, "Eightbound", 155, "Eightbound eviscerators"),
      u(3, "Exalted Eightbound", 165, "Paired eightbound chainfists"),
      u(1, "Rhino", 75, "Combi-bolter"),
      u(1, "Land Raider", 240, "Twin lascannons"),
    ],
  },
];
