// Offline-first service worker: precaches the app shell + every mission card and
// terrain layout (list generated by scripts/download-assets.mjs into assets/manifest.json),
// so the app keeps working with no signal at the venue.

const CACHE = "emperors-tarot-v1";

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      await cache.add("./");
      try {
        const res = await fetch("assets/manifest.json");
        const files = await res.json();
        await cache.put("assets/manifest.json", res.clone());
        // Cache images best-effort in chunks; a single 404 must not abort install.
        for (let i = 0; i < files.length; i += 10) {
          await Promise.allSettled(files.slice(i, i + 10).map((f) => cache.add(f)));
        }
      } catch (e) {}
      self.skipWaiting();
    })()
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        if (key !== CACHE) await caches.delete(key);
      }
      self.clients.claim();
    })()
  );
});

// Same-origin: network-first for the shell (fresh data when online), cache fallback offline.
// Cross-origin images (gdmissions.app fallbacks): cache-first.
self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const sameOrigin = new URL(req.url).origin === location.origin;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      if (!sameOrigin) {
        const cached = await cache.match(req);
        if (cached) return cached;
        const res = await fetch(req);
        if (res.ok) cache.put(req, res.clone());
        return res;
      }
      try {
        const res = await fetch(req);
        if (res.ok) cache.put(req, res.clone());
        return res;
      } catch (e) {
        const cached = await cache.match(req, { ignoreSearch: true });
        if (cached) return cached;
        throw e;
      }
    })()
  );
});
