// Shark Games Septiembre 2026 — roster from BCP event 7XKdC5R56bUG, pulled 2026-09-12.
// Roster gaps filled by the TO: Carlos Lara (Orks · Take and Hold),
// Alvarito Loki (Thousand Sons · Priority Assets), Antonio Carlos Vela (Tyranids · Take and Hold).

const u = (qty, name, pts, gear) => ({ qty, name, pts, gear });

export const EVENT = {
  id: "shark-sept-2026",
  name: "Shark Games Septiembre",
  storage: "shark-sept-2026",
  defaultMeId: "forthemperor",
  points: 2000,
  players: [
    {
      id: "adrian", name: "Adrián Blázquez Jiménez", team: "Los Angeles Orkos de Khorne",
      faction: "Chaos Knights", dispo: "Priority Assets",
      summary: { detachment: "Infernal Lance", warlord: "Chaos Cerastus Knight Lancer", points: 1980, units: 9, enhancements: ["Bestial Aspect (Desecrator)", "Blasphemous Engine (Rampager)"], secondaries: "" },
      list: [
        u(1, "Chaos Cerastus Knight Lancer", 385, "Warlord, Cerastus shock lance"),
        u(1, "Knight Desecrator", 385, "Bestial Aspect, Desecrator laser destructor, Warpstrike claw"),
        u(1, "Knight Rampager", 390, "Blasphemous Engine, Reaper chainsword, Warpstrike claw"),
        u(1, "War Dog Executioner", 130, "2x War dog autocannon, Daemonbreath meltagun"),
        u(1, "War Dog Executioner", 130, "2x War dog autocannon, Daemonbreath meltagun"),
        u(1, "War Dog Huntsman", 135, "Daemonbreath spear, Reaper chain talon"),
        u(1, "War Dog Huntsman", 135, "Daemonbreath spear, Reaper chain talon"),
        u(1, "War Dog Karnivore", 145, "Slaughterclaw, Reaper chaintalon"),
        u(1, "War Dog Karnivore", 145, "Slaughterclaw, Reaper chaintalon"),
      ],
    },
    {
      id: "alvarito", name: "Alvarito Loki", team: "Gondor 40K",
      faction: "Thousand Sons", dispo: "Priority Assets",
      summary: { detachment: "Grand Coven", warlord: "Magnus the Red", points: 2000, units: 15, enhancements: ["Umbralefic Crystal (Infernal Master)", "Eldritch Vortex of E'Taph (Sorcerer)", "Incandaeum (Exalted Sorcerer)"], secondaries: "" },
      list: [
        u(1, "Infernal Master", 130, "Umbralefic Crystal, Fires of the Abyss — leads Rubrics"),
        u(5, "Rubric Marines", 100, "Warpflamers, soulreaper cannon"),
        u(1, "Sorcerer", 130, "Eldritch Vortex of E'Taph, Force weapon — leads Rubrics"),
        u(5, "Rubric Marines", 100, "Inferno boltguns, soulreaper cannon"),
        u(1, "Daemon Prince of Tzeentch with Wings", 170, "Hellforged weapons, Infernal cannon"),
        u(1, "Exalted Sorcerer on Disc of Tzeentch", 105, "Incandaeum, Arcane Fire, Prosperine khopesh"),
        u(1, "Magnus the Red", 455, "Warlord, Blade of Magnus, Tzeentch's Firestorm"),
        u(1, "Chaos Rhino", 80, "Havoc launcher, inferno combi-bolters"),
        u(2, "Chaos Spawn", 65, "Hideous mutations"),
        u(2, "Chaos Spawn", 65, "Hideous mutations"),
        u(1, "Defiler", 330, "Ectoplasma destructor, heavy reaper autocannons"),
        u(2, "Sekhetar Robots", 85, "Heavy warpflamers, hellfyre missile racks"),
        u(2, "Sekhetar Robots", 85, "Heavy warpflamers, hellfyre missile racks"),
        u(3, "Tzaangor Enlightened", 50, "Divining spears"),
        u(3, "Tzaangor Enlightened", 50, "Divining spears"),
      ],
    },
    {
      id: "angel-c", name: "Angel Cañamero", team: "El Ordo Autista",
      faction: "Blood Angels", dispo: "Take and Hold",
      summary: { detachment: "Stormlance Task Force & Vengeful Hosts", warlord: "Commander Dante", points: 2000, units: 18, enhancements: ["Portents of Wisdom (Chaplain)", "Orksbane (DC Captain)"], secondaries: "" },
      list: [
        u(1, "Commander Dante", 125, "Warlord, The Axe Mortalis — leads Vanguard Veterans"),
        u(10, "Vanguard Veteran Squad w/ Jump Packs", 220, "Master-crafted power weapons, plasma pistols"),
        u(1, "Chaplain", 75, "Portents of Wisdom, Crozius arcanum — leads Bladeguard"),
        u(1, "Sanguinary Priest", 75, "With Bladeguard"),
        u(6, "Bladeguard Veteran Squad", 170, "Master-crafted power weapons, neo-volkite pistol"),
        u(1, "Death Company Captain w/ Jump Pack", 95, "Orksbane, Power fist — leads Death Company"),
        u(5, "Death Company w/ Jump Packs", 115, "Chainswords, eviscerator, power fists"),
        u(1, "Captain with Jump Pack", 80, "Plasma pistol, Power fist — leads Sanguinary Guard"),
        u(3, "Sanguinary Guard", 120, "Encarmine spears, Sanguinary Banner"),
        u(1, "Captain with Jump Pack", 80, "Thunder hammer, Relic Shield — leads Sanguinary Guard"),
        u(3, "Sanguinary Guard", 120, "Encarmine blades, Sanguinary Banner"),
        u(1, "The Sanguinor", 120, "Encarmine broadsword"),
        u(5, "Intercessor Squad", 80, "Bolt rifles, grenade launcher, power fist"),
        u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, plasma pistol, power fist"),
        u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, plasma pistol, power fist"),
        u(1, "Baal Predator", 125, "Baal flamestorm cannon, heavy flamers"),
        u(1, "Land Speeder", 105, "Multi-melta, gatling cannon, Stormfury missiles"),
        u(1, "Land Speeder", 105, "Multi-melta, gatling cannon, Stormfury missiles"),
      ],
    },
    {
      id: "antoniocv", name: "Antonio Carlos Vela", team: "Los Boltgun del Metal",
      faction: "Tyranids", dispo: "Take and Hold",
      summary: { detachment: "Assimilation Swarm & Talons of the Norn Queen", warlord: "The Swarmlord", points: 1995, units: 12, enhancements: ["Synaptoprescience (Norn Assimilators)"], secondaries: "" },
      list: [
        u(1, "Hive Tyrant", 195, "Monstrous bonesword and lash whip"),
        u(1, "The Swarmlord", 210, "Warlord, Bone sabres, Synaptic pulse"),
        u(1, "Biovores", 60, "Spore Mine launcher"),
        u(1, "Neurolictor", 80, "Piercing claws and talons"),
        u(1, "Norn Assimilator", 280, "Synaptoprescience, Toxinjector Harpoon"),
        u(1, "Norn Assimilator", 300, "Synaptoprescience, Toxinjector Harpoon"),
        u(1, "Norn Assimilator", 300, "Synaptoprescience, Toxinjector Harpoon"),
        u(3, "Pyrovores", 100, "Flamespurts"),
        u(3, "Pyrovores", 100, "Flamespurts"),
        u(1, "Ripper Swarms", 30, "Chitinous claws and teeth"),
        u(6, "Tyrant Guard", 170, "Scything talons and rending claws"),
        u(6, "Tyrant Guard", 170, "Scything talons and rending claws"),
      ],
    },
    {
      id: "antoniojose", name: "Antonio José Muñoz Rojas", team: "—",
      faction: "Chaos Space Marines", dispo: "Purge the Foe",
      summary: { detachment: "Creations of Bile", warlord: "Fabius Bile", points: 1995, units: 14, enhancements: ["Helm of All-Seeing (Master of Possession)", "Living Carapace (Chaos Lord)", "Prime Test Subject (Reave-Captain)"], secondaries: "" },
      list: [
        u(1, "Fabius Bile", 100, "Warlord, Rod of Torment, Xyclos Needler — leads Chosen"),
        u(10, "Chosen", 270, "Accursed weapons, combi-weapons, plasma pistols"),
        u(1, "Master of Executions", 70, "Axe of dismemberment — with Nemesis Claw"),
        u(10, "Nemesis Claw", 180, "Nostraman chainglaive, Voice Eater, heavy bolter, meltagun"),
        u(1, "Master of Possession", 85, "Helm of All-Seeing, Rite of Possession — leads Possessed"),
        u(5, "Possessed", 120, "Hideous mutations, icon"),
        u(1, "Chaos Lord with Jump Pack", 95, "Living Carapace, Twin lightning claws — leads Raptors"),
        u(10, "Raptors", 210, "Heavy melee weapons, meltaguns, plasma pistols"),
        u(1, "Red Corsairs Reave-Captain", 95, "Prime Test Subject, Power maul"),
        u(1, "Chaos Rhino", 65, "Combi-bolter, combi-weapon"),
        u(1, "Chaos Land Raider", 220, "Soulshatter lascannons, havoc launcher"),
        u(3, "Mutilators", 165, "Fleshmetal weapons"),
        u(5, "Red Corsairs Raiders", 110, "Reaver's blades, meltagun, power fist"),
        u(10, "Red Corsairs Raiders", 210, "Reaver's blades, meltaguns, power fists"),
      ],
    },
    {
      id: "basto", name: "Basto AJ", team: "—",
      faction: "Blood Angels", dispo: "Take and Hold",
      summary: { detachment: "Vengeful Hosts & Stormlance Task Force", warlord: "Commander Dante", points: 2000, units: 15, enhancements: ["Azorkte (Captain w/ Jump Pack)"], secondaries: "" },
      list: [
        u(1, "Commander Dante", 125, "Warlord, The Axe Mortalis — leads Vanguard Veterans"),
        u(10, "Vanguard Veteran Squad w/ Jump Packs", 220, "Master-crafted power weapons, plasma pistols"),
        u(1, "Lemartes", 100, "The Blood Crozius — leads Death Company"),
        u(10, "Death Company w/ Jump Packs", 230, "Chainswords, eviscerators, power fists"),
        u(1, "Captain with Jump Pack", 100, "Azorkte, Relic weapon — leads Sanguinary Guard"),
        u(6, "Sanguinary Guard", 260, "Encarmine blades, Angelus boltguns, banner"),
        u(1, "The Sanguinor", 120, "Encarmine broadsword"),
        u(5, "Assault Intercessor Squad", 80, "Chainswords, plasma pistol, power fist"),
        u(5, "Assault Intercessor Squad", 80, "Chainswords, plasma pistol, power fist"),
        u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, plasma pistol, power fist"),
        u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, plasma pistol, power fist"),
        u(1, "Baal Predator", 125, "Baal flamestorm cannon, heavy flamers"),
        u(3, "Sanguinary Guard", 120, "Encarmine spears, banner"),
        u(5, "Scout Squad", 65, "Combat knives, bolt pistols"),
        u(1, "Vindicator", 185, "Demolisher cannon"),
      ],
    },
    {
      id: "boris-b", name: "Boris Battikhi", team: "FIGHT CLUB",
      faction: "Orks", dispo: "Reconnaissance",
      summary: { detachment: "Bully Boyz, Kult of Speed & Wreckas", warlord: "Nazdreg", points: 2000, units: 18, enhancements: ["Kaptin's Hat (Mek)"], secondaries: "" },
      list: [
        u(1, "Nazdreg", 175, "Warlord, Kustom Blasta X, Moonchewa — leads Meganobz"),
        u(5, "Meganobz", 185, "Kustom shootas, power klaws"),
        u(1, "Mek", 70, "Kaptin's Hat, Kustom mega-slugga — leads Flash Gitz"),
        u(5, "Flash Gitz", 105, "Snazzguns"),
        u(1, "Big Mek Dakkarig", 135, "Blitzkannon, multi-busta launcha"),
        u(1, "Big Mek Dakkarig", 135, "Blitzkannon, multi-busta launcha"),
        u(1, "Wazdakka Gutsmek", 200, "Psyko-gatler, Grabba Dragga"),
        u(3, "Warbikers", 75, "Dual dakkaguns, kombi-rokkit"),
        u(3, "Warbikers", 75, "Dual dakkaguns, kombi-rokkit"),
        u(1, "Trukk", 60, "Dual big shoota, spiked ram"),
        u(1, "Trukk", 60, "Dual big shoota, spiked ram"),
        u(3, "Deffkoptas", 80, "Rokkit launchas, spinnin' blades"),
        u(3, "Deffkoptas", 80, "Rokkit launchas, spinnin' blades"),
        u(5, "Flash Gitz", 105, "Snazzguns"),
        u(10, "Gretchin", 45, "Grot blastas"),
        u(10, "Kommandos", 125, "Choppas, sluggas"),
        u(6, "Tankbustas", 145, "Busta rokkit launchas"),
        u(6, "Tankbustas", 145, "Busta rokkit launchas"),
      ],
    },
    {
      id: "capitan", name: "Capitán Mechero", team: "El Ordo Autista",
      faction: "Adeptus Mechanicus", dispo: "Priority Assets",
      summary: { detachment: "Cohort Cybernetica & Forge Lords", warlord: "Belisarius Cawl", points: 1995, units: 16, enhancements: ["Vingh's Dynamic Programming (Datasmith)", "TL-4ø9 (Manipulus)", "Necromechanic (Enginseer)"], secondaries: "" },
      list: [
        u(1, "Cybernetica Datasmith", 50, "Vingh's Dynamic Programming, Power fist — leads Kastelans"),
        u(4, "Kastelan Robots", 300, "Incendine combustors, twin Kastelan fists"),
        u(1, "Tech-Priest Manipulus", 90, "TL-4ø9, Magnarail lance — leads Breachers"),
        u(3, "Kataphron Breachers", 150, "Heavy arc rifles, arc claws"),
        u(1, "Belisarius Cawl", 220, "Warlord, Solar atomiser, Cawl's Omnissian axe"),
        u(1, "Tech-Priest Enginseer", 75, "Necromechanic, Omnissian axe"),
        u(1, "Thulia Ghuld", 180, "Rod of the War Forge, Jericho conversion resonator"),
        u(10, "Skitarii Rangers", 85, "Galvanic rifles, transuranic arquebus, plasma caliver"),
        u(2, "Ironstrider Ballistarii", 160, "Twin cognis autocannons"),
        u(2, "Ironstrider Ballistarii", 180, "Twin cognis lascannons"),
        u(1, "Onager Dunecrawler", 155, "Neutron laser"),
        u(3, "Serberys Raiders", 60, "Galvanic carbines, cavalry sabres"),
        u(9, "Servitor Battleclade", 65, "Heavy arc rifle, heavy bolter, servo-claws"),
        u(5, "Sicarian Infiltrators", 75, "Flechette blasters, taser goads"),
        u(5, "Sicarian Infiltrators", 75, "Flechette blasters, taser goads"),
        u(5, "Sicarian Ruststalkers", 75, "Transonic razors and chordclaws"),
      ],
    },
    {
      id: "carlitros", name: "Carlitros Morgado", team: "Los Boqueronestealers y el Chiringuito Colmena",
      faction: "Tyranids", dispo: "Reconnaissance",
      summary: { detachment: "Ambush Predators & Vanguard Onslaught", warlord: "The Swarmlord", points: 2000, units: 18, enhancements: ["Neuronode (Neurotyrant)", "Encircling Horrors (Von Ryan's Leapers)"], secondaries: "" },
      list: [
        u(1, "Broodlord", 80, "Claws and talons — leads Genestealers"),
        u(10, "Genestealers", 140, "Claws and talons"),
        u(1, "Broodlord", 80, "Claws and talons — leads Genestealers"),
        u(10, "Genestealers", 140, "Claws and talons"),
        u(5, "Hyperadapted Raveners", 165, "Prime claws, venom bolt — lead Raveners"),
        u(5, "Raveners", 125, "Claws and talons"),
        u(1, "Neurotyrant", 150, "Neuronode, Psychic scream — leads Zoanthropes"),
        u(6, "Zoanthropes", 190, "Warp Blasts, neurothrope"),
        u(1, "Deathleaper", 80, "Lictor claws and talons"),
        u(1, "The Swarmlord", 210, "Warlord, Bone sabres, Synaptic pulse"),
        u(10, "Hormagaunts", 70, "Hormagaunt talons"),
        u(1, "Biovores", 60, "Spore Mine launcher"),
        u(1, "Lictor", 60, "Lictor claws and talons"),
        u(1, "Lictor", 60, "Lictor claws and talons"),
        u(1, "Neurolictor", 80, "Piercing claws and talons"),
        u(1, "Neurolictor", 80, "Piercing claws and talons"),
        u(6, "Von Ryan's Leapers", 125, "Encircling Horrors, leaper's talons"),
        u(6, "Von Ryan's Leapers", 105, "Leaper's talons"),
      ],
    },
    {
      id: "carloslara", name: "Carlos Lara García", team: "Los Boltgun del Metal",
      faction: "Orks", dispo: "Take and Hold",
      summary: { detachment: "Arrazadorez, Brigada Datake y Peña de Drezs", warlord: "Ghazghkull Thraka", points: 2000, units: 14, enhancements: ["Kasko de Kapitán (Kabezilla)", "Paztor de drez (Mechadakka)"], secondaries: "" },
      list: [
        u(1, "MekánikO kon kañón de atake shokk", 95, "Kañón de atake shokk — leads Petatankez"),
        u(6, "Petatankez", 145, "Lanzakobetez ezplozivoz, pinchapeña"),
        u(1, "Ghazghkull Thraka", 300, "Warlord, Garra de Gorko, Rugío de Morko"),
        u(1, "Kabezilla", 110, "Kasko de Kapitán, Garra Trinkabeztiaz"),
        u(1, "Mechadakka de Mekániko", 155, "Paztor de drez, Kañón vapuleador"),
        u(10, "Chikoz Trinkabeztiaz", 85, "Piztolas, rebanadoras"),
        u(10, "Gretchin", 45, "Pipas de kanijo"),
        u(1, "Karro de Guerra", 160, "Kacharroz pa apuntar, akribilladorez pezados, bola de demolizión"),
        u(1, "Kazaforkma", 175, "Retumbador del jefe, kañón de arponez"),
        u(6, "Lataz Azezinaz", 260, "Garraz y lanzarrayoz pa Lataz"),
        u(10, "Orkomandoz", 125, "Rebanadoras, achicharrador, rompemuroz"),
        u(5, "Tipejoz Vazilonez", 105, "Mazakradorez molones"),
        u(5, "Tipejoz Vazilonez", 105, "Mazakradorez molones"),
        u(6, "Tronchadorez", 135, "Martillos aplaztadores"),
      ],
    },
    {
      id: "cristobal", name: "Cristobal Rosales", team: "—",
      faction: "Astra Militarum", dispo: "Priority Assets",
      summary: { detachment: "Grizzled Company", warlord: "Lord Solar Leontus", points: 1990, units: 14, enhancements: [], secondaries: "" },
      list: [
        u(1, "Commissar Yarrick", 120, "Bale Eye, Power klaw"),
        u(1, "Lord Solar Leontus", 130, "Warlord, Conquest, Sol's Righteous Gaze"),
        u(1, "Rogal Dorn Commander", 290, "Twin battle cannon, Castigator gatling cannon"),
        u(1, "Chimera", 75, "Multi-laser, heavy bolter"),
        u(1, "Artillery Team", 95, "Heavy mortar"),
        u(5, "Attilan Rough Riders", 60, "Hunting lances"),
        u(5, "Attilan Rough Riders", 60, "Hunting lances"),
        u(1, "Hippogriff AFV", 70, "Vigilator cannon"),
        u(1, "Hippogriff AFV", 70, "Vigilator cannon"),
        u(1, "Leman Russ Battle Tank", 165, "Battle cannon, lascannon"),
        u(1, "Manticore", 150, "Storm eagle rockets"),
        u(1, "Manticore", 170, "Storm eagle rockets"),
        u(1, "Rogal Dorn Battle Tank", 260, "Twin battle cannon, Castigator gatling cannon"),
        u(1, "Rogal Dorn Battle Tank", 275, "Twin battle cannon, Castigator gatling cannon"),
      ],
    },
    {
      id: "danmartina", name: "Dan Martina", team: "Los Boqueronestealers y el Chiringuito Colmena",
      faction: "Chaos Knights", dispo: "Reconnaissance",
      summary: { detachment: "Houndpack Lance & Hunting Warpack", warlord: "War Dog Brigand", points: 2000, units: 14, enhancements: ["Final Howl (Brigand)", "Preyslayer's Mantle (Karnivore)", "Snarling Rivalry (Executioners)"], secondaries: "" },
      list: [
        u(1, "War Dog Brigand", 135, "Warlord, Avenger chaincannon, Daemonbreath spear"),
        u(1, "War Dog Brigand", 155, "Final Howl, Avenger chaincannon"),
        u(1, "War Dog Karnivore", 160, "Preyslayer's Mantle, Slaughterclaw"),
        u(1, "War Dog Brigand", 135, "Avenger chaincannon, Daemonbreath spear"),
        u(1, "War Dog Brigand", 135, "Avenger chaincannon, Daemonbreath spear"),
        u(1, "War Dog Executioner", 140, "Snarling Rivalry, 2x War Dog autocannon"),
        u(1, "War Dog Executioner", 140, "Snarling Rivalry, 2x War Dog autocannon"),
        u(1, "War Dog Executioner", 140, "Snarling Rivalry, 2x War Dog autocannon"),
        u(1, "War Dog Karnivore", 145, "Slaughterclaw, Reaper chaintalon"),
        u(1, "War Dog Karnivore", 145, "Slaughterclaw, Reaper chaintalon"),
        u(1, "War Dog Karnivore", 145, "Slaughterclaw, Reaper chaintalon"),
        u(1, "War Dog Karnivore", 145, "Slaughterclaw, Reaper chaintalon"),
        u(1, "War Dog Karnivore", 145, "Slaughterclaw, Reaper chaintalon"),
        u(1, "War Dog Stalker", 135, "Avenger chaincannon, Slaughterclaw"),
      ],
    },
    {
      id: "danielmm", name: "Daniel Martin Millet", team: "Los Boqueronestealers y el Chiringuito Colmena",
      faction: "Drukhari", dispo: "Purge the Foe",
      summary: { detachment: "Reaper's Wager", warlord: "Lady Malys", points: 2000, units: 19, enhancements: ["Webway Walker (Archon)", "Archraider (Succubus)"], secondaries: "" },
      list: [
        u(1, "Lady Malys", 100, "Warlord, Lady's Blade, Razor fan — leads Incubi"),
        u(5, "Incubi", 90, "Klaives, demiklaives"),
        u(1, "Drazhar", 85, "Executioner's demiklaives — leads Incubi"),
        u(5, "Incubi", 90, "Klaives, demiklaives"),
        u(1, "Archon", 95, "Webway Walker, Huskblade, Shadowfield — leads Kabalites"),
        u(10, "Kabalite Warriors", 110, "Splinter rifles, dark lance, blaster"),
        u(1, "Succubus", 65, "Archraider, Archite glaive — leads Wyches"),
        u(10, "Wyches", 90, "Hekatarii blades, blast pistol"),
        u(1, "Raider", 75, "Dark lance"),
        u(1, "Venom", 65, "2x Splinter cannon"),
        u(1, "Venom", 65, "2x Splinter cannon"),
        u(1, "Ravager", 125, "3x Dark lance"),
        u(1, "Ravager", 125, "3x Dark lance"),
        u(1, "Ravager", 125, "3x Dark lance"),
        u(5, "Scourges with Heavy Weapons", 130, "4x Dark lance"),
        u(5, "Scourges with Heavy Weapons", 130, "4x Dark lance"),
        u(5, "Scourges with Heavy Weapons", 135, "3x Dark lance, heat lance"),
        u(2, "Talos", 150, "Macro-scalpels, twin heat lances"),
        u(2, "Talos", 150, "Macro-scalpels, twin heat lances"),
      ],
    },
    {
      id: "mrnutrition", name: "Daniel MrNutrition", team: "Diario de un Recluta",
      faction: "Adeptus Custodes", dispo: "Take and Hold",
      summary: { detachment: "Lions of the Emperor", warlord: "Valerian", points: 2000, units: 14, enhancements: ["Superior Creation (Blade Champion)", "Admonimortis (Shield-Captain)"], secondaries: "" },
      list: [
        u(1, "Valerian", 110, "Warlord, Gnosis — leads Custodian Wardens"),
        u(5, "Custodian Wardens", 250, "Guardian spears, vexilla"),
        u(1, "Blade Champion", 135, "Superior Creation, Vaultswords — leads Custodian Guard"),
        u(4, "Custodian Guard", 170, "Guardian spears"),
        u(1, "Shield-Captain on Dawneagle Jetbike", 170, "Admonimortis, Interceptor lance — leads Praetors"),
        u(2, "Vertus Praetors", 145, "Interceptor lances, hurricane bolters"),
        u(4, "Custodian Guard", 170, "Guardian spears"),
        u(4, "Custodian Guard", 170, "Guardian spears"),
        u(6, "Allarus Custodians", 340, "Guardian spears, balistus grenade launchers"),
        u(4, "Prosecutors", 45, "Boltguns"),
        u(2, "Vertus Praetors", 145, "Interceptor lances, hurricane bolters"),
        u(4, "Vigilators", 50, "Executioner greatblades"),
        u(4, "Vigilators", 50, "Executioner greatblades"),
        u(4, "Witchseekers", 50, "Witchseeker flamers"),
      ],
    },
    {
      id: "davidespejo", name: "David Espejo", team: "Don't Cry",
      faction: "Orks", dispo: "Take and Hold",
      summary: { detachment: "Enjambre Kanijo, Marea Verde y Peña de Drezs", warlord: "Wazdakka Gutsmek", points: 2000, units: 20, enhancements: ["Servicio en el campo de minas (Gretchin)", "Paztor de drez (Mechadakka)"], secondaries: "" },
      list: [
        u(1, "Kaudillo", 100, "Akribillador ezpezial — leads Chikoz"),
        u(1, "Chapuzaz", 45, "With Chikoz"),
        u(10, "Chikoz", 90, "Akribilladorez, rebanadoras"),
        u(1, "Kaudillo", 100, "Akribillador ezpezial — leads Chikoz"),
        u(1, "Jefazo", 50, "Gran rebanadora — with Chikoz"),
        u(20, "Chikoz", 180, "Akribilladorez, rebanadoras"),
        u(1, "Zodgrod Verrugozgrod", 50, "Atrapakuellloz — leads Gretchin"),
        u(1, "Kaporal", 10, "With Gretchin"),
        u(20, "Gretchin", 90, "Servicio en el campo de minas, pipas de kanijo"),
        u(1, "Mechadakka de Mekániko", 135, "Kañón vapuleador"),
        u(1, "Mechadakka de Mekániko", 155, "Paztor de drez, Kañón vapuleador"),
        u(1, "Wazdakka Gutsmek", 200, "Warlord, Zikopatralladora, Kogearraztra"),
        u(1, "Kamión", 60, "Akribillador pezado dual"),
        u(1, "Buguiz de Guerra", 70, "Dakka eztra"),
        u(1, "Buguiz de Guerra", 70, "Dakka eztra"),
        u(1, "Dreznaut", 130, "Garraz pa Drez, kemakema"),
        u(3, "Lataz Azezinaz", 130, "Garraz y lanzarrayoz pa Lataz"),
        u(3, "Moteroz", 75, "Ametralladoraz duales"),
        u(10, "Orkomandoz", 125, "Rebanadoras, achicharrador, rompemuroz"),
        u(6, "Tronchadorez", 135, "Martillos aplaztadores, nudilloz kabum"),
      ],
    },
    {
      id: "davidruiz", name: "David Ruiz Muñoz", team: "Gondor 40K",
      faction: "Adeptus Custodes", dispo: "Take and Hold",
      summary: { detachment: "Might of the Moritoi & Shield Host", warlord: "Blade Champion", points: 2000, units: 14, enhancements: ["Castellan's Mark (Shield-Captain)", "Panoptispex (Shield-Captain)"], secondaries: "" },
      list: [
        u(1, "Blade Champion", 110, "Warlord, Vaultswords — leads Custodian Guard"),
        u(4, "Custodian Guard", 170, "Guardian spears"),
        u(1, "Shield-Captain in Allarus Terminator Armour", 150, "Castellan's Mark, Guardian spear — leads Allarus"),
        u(5, "Allarus Custodians", 280, "Guardian spears, balistus grenade launchers"),
        u(1, "Shield-Captain on Dawneagle Jetbike", 145, "Panoptispex, Interceptor lance — leads Praetors"),
        u(2, "Vertus Praetors", 145, "Interceptor lances, salvo launchers"),
        u(5, "Custodian Guard", 215, "Guardian spears, praesidium shield, vexilla"),
        u(4, "Custodian Guard", 170, "Guardian spears, praesidium shield, vexilla"),
        u(4, "Prosecutors", 45, "Boltguns"),
        u(4, "Prosecutors", 45, "Boltguns"),
        u(4, "Prosecutors", 45, "Boltguns"),
        u(3, "Venatari Custodians", 165, "Venatari lances"),
        u(1, "Venerable Contemptor Dreadnought", 170, "Multi-melta, combat weapon"),
        u(2, "Vertus Praetors", 145, "Interceptor lances, salvo launchers"),
      ],
    },
    {
      id: "eduardo", name: "Eduardo Aparicio", team: "Don't Cry",
      faction: "Aeldari", dispo: "Priority Assets",
      summary: { detachment: "Aspect Host", warlord: "Avatar of Khaine", points: 1980, units: 18, enhancements: [], secondaries: "" },
      list: [
        u(1, "Avatar of Khaine", 250, "Warlord, the Wailing Doom"),
        u(1, "Eldrad Ulthran", 120, "Mind war, Staff of Ulthamar — leads Storm Guardians"),
        u(11, "Storm Guardians", 100, "Fusion guns, flamers, serpent shield platform"),
        u(1, "Farseer Skyrunner", 60, "Eldritch storm, singing spear — leads Windriders"),
        u(3, "Windriders", 80, "Shuriken cannons"),
        u(5, "Howling Banshees", 85, "Banshee blades, executioner"),
        u(1, "Jain Zar", 105, "Blade of destruction, Silent death"),
        u(1, "Lhykhis", 135, "Weaverender, spider's fangs — leads Warp Spiders"),
        u(5, "Warp Spiders", 105, "Death spinners"),
        u(1, "Farseer", 65, "Eldritch storm, singing spear"),
        u(1, "Spiritseer", 50, "Witch staff"),
        u(1, "Falcon", 130, "Bright lance, pulse laser"),
        u(1, "Wraithlord", 125, "2x Bright lance, ghostglaive"),
        u(5, "Dire Avengers", 70, "Avenger shuriken catapults"),
        u(5, "Fire Dragons", 120, "Dragon fusion guns, firepike"),
        u(5, "Swooping Hawks", 95, "Lasblasters, hawk's talon"),
        u(5, "Wraithblades", 140, "Ghostaxes and forceshields"),
        u(5, "Wraithguard", 145, "D-scythes"),
      ],
    },
    {
      id: "forthemperor", name: "For the Emperor", team: "Los Boqueronestealers y el Chiringuito Colmena",
      faction: "Death Guard", dispo: "Disruption",
      summary: { detachment: "Paragons of Putrescence & Shamblerot Vectorium", warlord: "Mortarion", points: 1975, units: 14, enhancements: ["Sorrowsyphon (Plaguecaster)", "Rejuvenating Swarm (Blightbringer)"], secondaries: "" },
      list: [
        u(1, "Malignant Plaguecaster", 70, "Sorrowsyphon, Plague Wind — leads Poxwalkers"),
        u(10, "Poxwalkers", 65, "Improvised weapons"),
        u(1, "Typhus", 100, "Lakrimae — leads Poxwalkers"),
        u(1, "Noxious Blightbringer", 70, "Rejuvenating Swarm, Cursed plague bell — with Poxwalkers"),
        u(20, "Poxwalkers", 130, "Improvised weapons"),
        u(1, "Malignant Plaguecaster", 60, "Plague Wind, Corrupted staff"),
        u(1, "Mortarion", 375, "Warlord, Silence, Lantern, Rotwind"),
        u(10, "Poxwalkers", 65, "Improvised weapons"),
        u(10, "Poxwalkers", 65, "Improvised weapons"),
        u(1, "Chaos Rhino", 75, "Combi-bolters, havoc launcher"),
        u(1, "Defiler", 330, "Hades battle cannon, excruciator cannons, shearing claws"),
        u(1, "Defiler", 380, "Hades battle cannon, excruciator cannons, shearing claws"),
        u(1, "Myphitic Blight-haulers", 95, "Multi-melta, missile launcher"),
        u(1, "Myphitic Blight-haulers", 95, "Multi-melta, missile launcher"),
      ],
    },
    {
      id: "franciscop", name: "Francisco Perez", team: "Gondor 40K",
      faction: "Emperor's Children", dispo: "Reconnaissance",
      summary: { detachment: "Carnival of Excess & Frenzied Host", warlord: "Lord Exultant", points: 1950, units: 18, enhancements: ["Warp Walker (Lord Exultant)", "Possessed Blade (Lord Exultant)", "Dark Blessings (Lord Exultant)"], secondaries: "" },
      list: [
        u(1, "Lord Exultant", 125, "Warlord, Warp Walker, Phoenix power spear — leads Infractors"),
        u(5, "Infractors", 85, "Duelling sabres, Icon of Excess"),
        u(1, "Lord Exultant", 125, "Possessed Blade, Phoenix power spear — leads Infractors"),
        u(5, "Infractors", 85, "Duelling sabres, Icon of Excess"),
        u(1, "Lord Exultant", 110, "Dark Blessings, Phoenix power spear — leads Infractors"),
        u(5, "Infractors", 85, "Duelling sabres, Icon of Excess"),
        u(10, "Daemonettes", 100, "Slashing claws, icon, instrument"),
        u(10, "Daemonettes", 100, "Slashing claws, icon, instrument"),
        u(10, "Daemonettes", 100, "Slashing claws, icon, instrument"),
        u(5, "Tormentors", 80, "Meltagun, plasma gun, Icon of Excess"),
        u(1, "Chaos Rhino", 70, "Combi-bolter, havoc launcher"),
        u(1, "Chaos Rhino", 70, "Combi-bolter, havoc launcher"),
        u(2, "Chaos Spawn", 70, "Hideous mutations"),
        u(1, "Defiler", 330, "Ectoplasma destructor, heavy reaper autocannons"),
        u(3, "Fiends", 90, "Barbed tails and dissecting claws"),
        u(1, "Maulerfiend", 120, "Maulerfiend fists, magma cutters"),
        u(1, "Maulerfiend", 120, "Maulerfiend fists, magma cutters"),
        u(5, "Seekers", 85, "Lashing tongues, icon, instrument"),
      ],
    },
    {
      id: "franxu", name: "Franxu Cortes", team: "Los Boqueronestealers y el Chiringuito Colmena",
      faction: "Adeptus Custodes", dispo: "Take and Hold",
      summary: { detachment: "Might of the Moritoi & Shield Host", warlord: "Trajann Valoris", points: 2000, units: 13, enhancements: ["Panoptispex (Shield-Captain)"], secondaries: "" },
      list: [
        u(1, "Trajann Valoris", 135, "Warlord, Watcher's Axe — leads Custodian Wardens"),
        u(4, "Custodian Wardens", 220, "Guardian spears, vexilla"),
        u(1, "Shield-Captain", 115, "Panoptispex, Guardian spear — leads Custodian Guard"),
        u(4, "Custodian Guard", 170, "Guardian spears, praesidium shield, vexilla"),
        u(1, "Blade Champion", 110, "Vaultswords — leads Custodian Wardens"),
        u(4, "Custodian Wardens", 200, "Guardian spears, vexilla"),
        u(1, "Valerian", 110, "Gnosis — leads Custodian Wardens"),
        u(4, "Custodian Wardens", 220, "Guardian spears, vexilla"),
        u(4, "Custodian Guard", 170, "Guardian spears, praesidium shield, vexilla"),
        u(4, "Prosecutors", 45, "Boltguns"),
        u(4, "Prosecutors", 45, "Boltguns"),
        u(1, "Venerable Land Raider", 220, "Godhammer lascannons"),
        u(1, "Venerable Land Raider", 240, "Godhammer lascannons"),
      ],
    },
    {
      id: "hugo", name: "Hugo Barroso", team: "—",
      faction: "Blood Angels", dispo: "Take and Hold",
      summary: { detachment: "Liberator Assault Group", warlord: "Commander Dante", points: 1995, units: 13, enhancements: [], secondaries: "" },
      list: [
        u(1, "Captain with Jump Pack", 80, "Thunder hammer, Relic Shield"),
        u(1, "Captain with Jump Pack", 80, "Thunder hammer, Relic Shield"),
        u(1, "Commander Dante", 125, "Warlord, The Axe Mortalis, Perdition Pistol"),
        u(1, "Lemartes", 100, "The Blood Crozius"),
        u(5, "Intercessor Squad", 80, "Bolt rifles"),
        u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, plasma pistol"),
        u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, plasma pistol"),
        u(1, "Ballistus Dreadnought", 150, "Ballistus lascannon & missile launcher"),
        u(10, "Death Company w/ Jump Packs", 230, "Chainswords, eviscerators, power fists"),
        u(1, "Gladiator Lancer", 160, "Lancer laser destroyer"),
        u(6, "Sanguinary Guard", 260, "Encarmine spears, Angelus boltguns"),
        u(6, "Sanguinary Guard", 260, "Encarmine blades, Angelus boltguns"),
        u(6, "Sanguinary Guard", 280, "Encarmine blades, Angelus boltguns"),
      ],
    },
    {
      id: "jorge", name: "Jorge Ransom", team: "Los Boqueronestealers y el Chiringuito Colmena",
      faction: "Thousand Sons", dispo: "Priority Assets",
      summary: { detachment: "Grand Coven (Kindred Sorcery)", warlord: "Magnus the Red", points: 2000, units: 17, enhancements: ["Umbralefic Crystal (Exalted Sorcerer)", "Incandeum (Exalted Sorcerer)", "Eldritch Vortex of E'taph (Infernal Master)"], secondaries: "Bring It Down: (4x2) + (1x4) — Assassination: 5 Characters" },
      list: [
        u(1, "Exalted Sorcerer", 125, "Umbralefic Crystal, Astral Blast — leads Rubrics"),
        u(1, "Exalted Sorcerer", 110, "Incandeum, Astral Blast — leads Rubrics"),
        u(1, "Infernal Master", 135, "Eldritch Vortex of E'taph, Fires of the Abyss — leads Rubrics"),
        u(1, "Magnus the Red", 455, "Warlord, Blade of Magnus, Tzeentch's Firestorm"),
        u(1, "Sorcerer", 95, "Pandaemonic Delusion, Prosperine khopesh — leads Rubrics"),
        u(5, "Rubric Marines", 100, "Inferno boltguns, soulreaper cannon"),
        u(5, "Rubric Marines", 100, "Warpflamers, soulreaper cannon"),
        u(5, "Rubric Marines", 100, "Warpflamers, soulreaper cannon"),
        u(5, "Rubric Marines", 110, "Warpflamers, soulreaper cannon"),
        u(1, "Chaos Rhino", 80, "Havoc launcher, inferno combi-bolter"),
        u(2, "Chaos Spawn", 65, "Hideous mutations"),
        u(2, "Chaos Spawn", 65, "Hideous mutations"),
        u(2, "Chaos Spawn", 65, "Hideous mutations"),
        u(1, "Mutalith Vortex Beast", 170, "Warp vortex, mutalith claws"),
        u(2, "Sekhetar Robots", 85, "Heavy warpflamers, hellfyre missile racks"),
        u(2, "Sekhetar Robots", 85, "Heavy warpflamers, hellfyre missile racks"),
        u(3, "Tzaangor Enlightened", 55, "Fatecaster greatbows"),
      ],
    },
    {
      id: "juanjo", name: "Juanjo Wu", team: "Gondor 40K",
      faction: "Blood Angels", dispo: "Take and Hold",
      summary: { detachment: "Liberator Assault Group", warlord: "Commander Dante", points: 2000, units: 17, enhancements: ["Rage-fuelled Warrior (Captain w/ Jump Pack)", "Gift of Foresight (Lieutenant)"], secondaries: "" },
      list: [
        u(1, "Commander Dante", 125, "Warlord, The Axe Mortalis — leads Sanguinary Guard"),
        u(6, "Sanguinary Guard", 260, "Encarmine blades, Angelus boltguns, banner"),
        u(1, "Lemartes", 100, "The Blood Crozius — leads Death Company"),
        u(10, "Death Company w/ Jump Packs", 230, "Chainswords, eviscerators, power fists"),
        u(1, "Captain with Jump Pack", 115, "Rage-fuelled Warrior, Thunder hammer — leads Sanguinary Guard"),
        u(3, "Sanguinary Guard", 120, "Encarmine blades, banner"),
        u(1, "Chief Librarian Mephiston", 110, "Vitarus, Fury of the Ancients"),
        u(1, "Lieutenant with Combi-weapon", 110, "Gift of Foresight, Paired combat blades"),
        u(5, "Assault Intercessor Squad", 80, "Chainswords, plasma pistol, power fist"),
        u(5, "Assault Intercessor Squad", 80, "Chainswords, plasma pistol, power fist"),
        u(5, "Intercessor Squad", 80, "Bolt rifles"),
        u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, hand flamer, power fist"),
        u(5, "Assault Intercessors w/ Jump Packs", 95, "Chainswords, hand flamer, power fist"),
        u(1, "Baal Predator", 125, "Baal flamestorm cannon, heavy flamers"),
        u(1, "Land Speeder", 105, "Multi-melta, gatling cannon, Stormfury missiles"),
        u(1, "Land Speeder", 105, "Multi-melta, gatling cannon, Stormfury missiles"),
        u(5, "Scout Squad", 65, "Boltguns"),
      ],
    },
    {
      id: "juanma", name: "Juanma Melilla", team: "Diario de un Recluta",
      faction: "Adeptus Custodes", dispo: "Take and Hold",
      summary: { detachment: "Lions of the Emperor", warlord: "Shield-Captain on Dawneagle Jetbike", points: 1990, units: 11, enhancements: ["Admonimortis (Shield-Captain)", "Fierce Conqueror (Shield-Captain)"], secondaries: "" },
      list: [
        u(1, "Shield-Captain on Dawneagle Jetbike", 170, "Warlord, Admonimortis, Interceptor lance — leads Praetors"),
        u(3, "Vertus Praetors", 215, "Interceptor lances, hurricane bolters"),
        u(1, "Blade Champion", 110, "Vaultswords — leads Custodian Wardens"),
        u(5, "Custodian Wardens", 250, "Guardian spears, vexilla"),
        u(1, "Shield-Captain on Dawneagle Jetbike", 155, "Fierce Conqueror, Interceptor lance — leads Praetors"),
        u(3, "Vertus Praetors", 215, "Interceptor lances, hurricane bolters"),
        u(1, "Shield-Captain on Dawneagle Jetbike", 140, "Interceptor lance — leads Praetors"),
        u(2, "Vertus Praetors", 170, "Interceptor lances, hurricane bolters"),
        u(4, "Custodian Guard", 170, "Guardian spears, praesidium shield, vexilla"),
        u(6, "Allarus Custodians", 340, "Guardian spears, balistus grenade launchers"),
        u(5, "Vigilators", 55, "Executioner greatblades"),
      ],
    },
    {
      id: "leo", name: "Leo Torres", team: "—",
      faction: "Necrons", dispo: "Purge the Foe",
      summary: { detachment: "Cursed Legion & Hand of the Dynasty", warlord: "Nekrosor Ammentar", points: 1995, units: 18, enhancements: ["Cursed Circlet (Skorpekh Lord)", "Destroyer Ankh (Command Barge)", "Mark of the Nekrosor (Hexmark)"], secondaries: "" },
      list: [
        u(1, "Technomancer", 80, "Staff of light — with Necron Warriors"),
        u(10, "Necron Warriors", 85, "Gauss reapers"),
        u(1, "Imotekh the Stormlord", 100, "Gauntlet of Fire — leads Necron Warriors"),
        u(1, "Psychomancer", 55, "Abyssal lance — with Necron Warriors"),
        u(10, "Necron Warriors", 85, "Gauss flayers"),
        u(1, "Skorpekh Lord", 120, "Cursed Circlet, Hyperphase harvester — leads Skorpekhs"),
        u(3, "Skorpekh Destroyers", 85, "Hyperphase weapons, plasmacyte"),
        u(1, "Catacomb Command Barge", 140, "Destroyer Ankh, Resurrection Orb"),
        u(1, "C'tan Shard of the Void Dragon", 345, "Spear of the Void Dragon, Voltaic storm"),
        u(1, "Hexmark Destroyer", 95, "Mark of the Nekrosor, Enmitic disintegrator pistols"),
        u(1, "Nekrosor Ammentar", 185, "Warlord, Unmaker Gauntlet, Nullstone Field"),
        u(3, "Canoptek Scarab Swarms", 40, "Feeder mandibles"),
        u(1, "Doomsday Ark", 210, "Doomsday cannon"),
        u(5, "Flayed Ones", 55, "Flayer claws"),
        u(1, "Lokhust Heavy Destroyers", 50, "Gauss destructor"),
        u(2, "Lokhust Heavy Destroyers", 100, "Gauss destructors"),
        u(3, "Ophydian Destroyers", 80, "Hyperphase weapons, plasmacyte"),
        u(3, "Skorpekh Destroyers", 85, "Hyperphase weapons, plasmacyte"),
      ],
    },
    {
      id: "manumtd", name: "Manu MyTinyDemons", team: "Los Boltgun del Metal",
      faction: "Drukhari", dispo: "Reconnaissance",
      summary: { detachment: "Exhibition of Slaughter & Skysplinter Assault", warlord: "Lady Malys", points: 2000, units: 22, enhancements: ["Nightmare Shroud (Archon)", "Periapt of Torments (Succubus)"], secondaries: "" },
      list: [
        u(1, "Lady Malys", 100, "Warlord, Lady's Blade, Razor fan — leads Incubi"),
        u(5, "Incubi", 90, "Klaives, demiklaives"),
        u(1, "Archon", 100, "Nightmare Shroud, Huskblade, Shadowfield — leads Hand of the Archon"),
        u(10, "Hand of the Archon", 115, "Blaster, dark lance, stimm-needler"),
        u(1, "Drazhar", 85, "Executioner's demiklaives — leads Incubi"),
        u(5, "Incubi", 90, "Klaives, demiklaives"),
        u(1, "Succubus", 70, "Periapt of Torments, Archite glaive — leads Wyches"),
        u(10, "Wyches", 90, "Hekatarii blades, blast pistol"),
        u(10, "Wyches", 90, "Hekatarii blades, blast pistol"),
        u(10, "Wyches", 90, "Hekatarii blades, blast pistol"),
        u(1, "Raider", 75, "Dark lance"),
        u(1, "Venom", 65, "2x Splinter cannon"),
        u(1, "Venom", 65, "2x Splinter cannon"),
        u(1, "Venom", 65, "2x Splinter cannon"),
        u(1, "Venom", 75, "2x Splinter cannon"),
        u(1, "Cronos", 55, "Spirit syphon"),
        u(10, "Hellions", 180, "Hellglaives, phantasm grenade launcher"),
        u(5, "Hellions", 90, "Hellglaives"),
        u(5, "Mandrakes", 80, "Baleblasts, glimmersteel blades"),
        u(1, "Ravager", 125, "3x Dark lance"),
        u(3, "Reavers", 75, "Heat lance, cluster caltrops"),
        u(5, "Scourges with Heavy Weapons", 130, "4x Dark lance"),
      ],
    },
    {
      id: "manuelg", name: "Manuel González", team: "Ñu Team",
      faction: "Necrons", dispo: "Reconnaissance",
      summary: { detachment: "Hypercrypt Legion & Skyshroud Spearhead", warlord: "Hexmark Destroyer", points: 1995, units: 12, enhancements: [], secondaries: "" },
      list: [
        u(1, "C'tan Shard of the Deceiver", 330, "Cosmic insanity, Golden fists"),
        u(1, "C'tan Shard of the Nightbringer", 360, "Gaze of death, Scythe of the Nightbringer"),
        u(1, "C'tan Shard of the Void Dragon", 345, "Spear of the Void Dragon, Voltaic storm"),
        u(1, "Hexmark Destroyer", 75, "Warlord, Enmitic disintegrator pistols"),
        u(1, "Transcendent C'tan", 340, "Crackling tendrils, Seismic assault"),
        u(1, "Canoptek Spyders", 65, "Particle beamers, gloom prism"),
        u(5, "Deathmarks", 60, "Synaptic disintegrators"),
        u(5, "Deathmarks", 60, "Synaptic disintegrators"),
        u(2, "Lokhust Heavy Destroyers", 100, "Enmitic exterminators"),
        u(2, "Lokhust Heavy Destroyers", 100, "Enmitic exterminators"),
        u(5, "Triarch Praetorians", 80, "Rods of covenant"),
        u(5, "Triarch Praetorians", 80, "Rods of covenant"),
      ],
    },
    {
      id: "pablos", name: "Pablo S", team: "FIGHT CLUB",
      faction: "Adepta Sororitas", dispo: "Priority Assets",
      summary: { detachment: "Hallowed Martyrs", warlord: "Morvenn Vahl", points: 2000, units: 17, enhancements: ["Through Suffering, Strength (Palatine)", "Saintly Example (Canoness)"], secondaries: "" },
      list: [
        u(1, "Morvenn Vahl", 200, "Warlord, Lance of Illumination — leads Paragons"),
        u(3, "Paragon Warsuits", 210, "Multi-meltas, war blades"),
        u(1, "Palatine", 75, "Through Suffering Strength — leads Insidiants"),
        u(10, "Celestian Insidiants", 120, "Null maces, condemnor bolt pistols"),
        u(1, "Junith Eruita", 105, "Mace of Castigation, twin heavy flamer — leads Sacresants"),
        u(10, "Celestian Sacresants", 150, "Hallowed maces"),
        u(1, "Canoness with Jump Pack", 85, "Saintly Example, Blessed halberd — leads Zephyrim"),
        u(5, "Zephyrim Squad", 75, "Power weapons, sacred banner"),
        u(3, "Saint Celestine", 150, "The Ardent Blade, Geminae Superia"),
        u(1, "Immolator", 100, "Immolation flamers"),
        u(1, "Immolator", 115, "Twin multi-melta"),
        u(1, "Sororitas Rhino", 65, "Storm bolter"),
        u(1, "Castigator", 165, "Castigator battle cannon"),
        u(10, "Dominion Squad", 110, "4x Meltagun, inferno pistol"),
        u(10, "Dominion Squad", 110, "4x Meltagun, inferno pistol"),
        u(5, "Seraphim Squad", 75, "Inferno pistols"),
        u(10, "Sisters Novitiate Squad", 90, "Novitiate melee weapons, flamers"),
      ],
    },
    {
      id: "rafa", name: "Rafa Gonzalez", team: "Los Boqueronestealers y el Chiringuito Colmena",
      faction: "Space Marines", dispo: "Take and Hold",
      summary: { detachment: "Ultramarines · Ceramite Sentinels", warlord: "Marneus Calgar", points: 2000, units: 14, enhancements: ["Honour Indefatigable (Captain in Gravis)"], secondaries: "" },
      list: [
        u(1, "Marneus Calgar in Armour of Antilochus", 155, "Warlord, Gauntlets of Ultramar — leads Wardens + Bladeguard"),
        u(6, "Wardens of Ultramar", 120, "Gadriel, Metaurus, Silva, Minervas, Komelius, Vestha"),
        u(6, "Bladeguard Veteran Squad", 160, "Master-crafted power weapons"),
        u(1, "Uriel Ventris", 105, "Invictus, Sword of Idaeus — leads Victrix Guard"),
        u(1, "Cato Sicarius", 105, "Talassarian tempest blade — with Victrix Guard"),
        u(6, "Victrix Honour Guard", 255, "Master-crafted power weapons, Banner of Macragge"),
        u(1, "Captain in Gravis Armour", 105, "Honour Indefatigable, Relic blade"),
        u(5, "Intercessor Squad", 80, "Bolt rifles, grenade launcher, power fist"),
        u(5, "Assault Intercessors w/ Jump Packs", 85, "Chainswords, plasma pistol, power fist"),
        u(1, "Ballistus Dreadnought", 150, "Ballistus lascannon & missile launcher"),
        u(5, "Incursor Squad", 85, "Occulus bolt carbines"),
        u(1, "Repulsor Executioner", 265, "Heavy laser destroyer, Icarus rocket pod"),
        u(1, "Repulsor Executioner", 265, "Heavy laser destroyer, Icarus rocket pod"),
        u(5, "Scout Squad", 65, "Missile launcher, sniper rifle"),
      ],
    },
    {
      id: "raul", name: "Raúl Enríquez", team: "Los Boltgun del Metal",
      faction: "Imperial Knights", dispo: "Take and Hold",
      summary: { detachment: "Questoris Companions", warlord: "Canis Rex", points: 2000, units: 6, enhancements: ["Pennant of Silvered Fury (Lancer)", "Wyrmslayer Divination (Crusader)"], secondaries: "" },
      list: [
        u(1, "Canis Rex", 415, "Warlord, Freedom's Hand, Las-impulsor"),
        u(1, "Cerastus Knight Atrapos", 405, "Graviton singularity cannon, Atrapos lascutter"),
        u(1, "Cerastus Knight Lancer", 430, "Pennant of Silvered Fury, Cerastus shock lance"),
        u(1, "Knight Crusader", 420, "Wyrmslayer Divination, Rapid-fire battle cannon, Avenger gatling"),
        u(1, "Knight Destrier", 265, "Chastiser gatling cannon, Frag bombard"),
        u(1, "Watch Captain Artemis (allied)", 65, "Hellfire Extremis"),
      ],
    },
    {
      id: "sergio", name: "Sergio Galán", team: "Legio Veteris",
      faction: "Orks", dispo: "Take and Hold",
      summary: { detachment: "Arrazadorez, Brigada Datake y Pilotorkz", warlord: "KaudillO kon megaarmadura", points: 2000, units: 16, enhancements: ["Kacharroz pa apuntar (Karros)"], secondaries: "" },
      list: [
        u(1, "MekánikO kon kañón de atake shokk", 95, "Kañón de atake shokk — leads Petatankez"),
        u(6, "Petatankez", 145, "Lanzakobetez ezplozivoz, pinchapeña"),
        u(1, "MekánikO kon kañón de atake shokk", 105, "Kañón de atake shokk — leads Petatankez"),
        u(6, "Petatankez", 145, "Lanzakobetez ezplozivoz, pinchapeña"),
        u(1, "Chapuzaz", 45, "With Tipejoz Vazilonez"),
        u(5, "Tipejoz Vazilonez", 105, "Mazakradorez molones"),
        u(1, "KaudillO kon megaarmadura", 125, "Warlord, Akribillador pezado, kacho rebanadora"),
        u(1, "Mechadakka de Mekániko", 135, "Kañón vapuleador"),
        u(1, "Mechadakka de Mekániko", 135, "Kañón vapuleador"),
        u(10, "Gretchin", 45, "Pipas de kanijo"),
        u(10, "Gretchin", 45, "Pipas de kanijo"),
        u(1, "Karro de Guerra", 160, "Kacharroz pa apuntar, akribilladorez pezados"),
        u(1, "Karro de Guerra", 160, "Kacharroz pa apuntar, akribilladorez pezados"),
        u(10, "Orkomandoz", 125, "Rebanadoras, achicharrador, rompemuroz"),
        u(1, "Zuperreaktor Tuneao", 215, "Blastajet Force Field, megalanzarrayoz"),
        u(1, "Zuperreaktor Tuneao", 215, "Blastajet Force Field, megalanzarrayoz"),
      ],
    },
    {
      id: "wofi", name: "wofi lopez", team: "Gondor 40K",
      faction: "Necrons", dispo: "Priority Assets",
      summary: { detachment: "Starshatter Arsenal", warlord: "The Silent King", points: 2000, units: 12, enhancements: ["Chrono-impedance Fields (Technomancer)"], secondaries: "" },
      list: [
        u(1, "Technomancer", 105, "Chrono-impedance Fields, Staff of light — leads Wraiths"),
        u(6, "Canoptek Wraiths", 220, "Particle casters, vicious claws"),
        u(1, "C'tan Shard of the Nightbringer", 360, "Gaze of death, Scythe of the Nightbringer"),
        u(1, "Nekrosor Ammentar", 185, "Unmaker Gauntlet, Nullstone Field"),
        u(1, "The Silent King", 420, "Warlord, Sceptre of Eternal Glory, 2x Triarchal Menhir"),
        u(5, "Immortals", 70, "Gauss blasters"),
        u(3, "Canoptek Scarab Swarms", 40, "Feeder mandibles"),
        u(3, "Canoptek Scarab Swarms", 40, "Feeder mandibles"),
        u(2, "Cryptothralls", 60, "Scouring eyes"),
        u(1, "Doomsday Ark", 210, "Doomsday cannon"),
        u(1, "Doomsday Ark", 210, "Doomsday cannon"),
        u(3, "Ophydian Destroyers", 80, "Hyperphase weapons"),
      ],
    },
  ],
};
